### ISSUE TITLE
Is the application suspended from maintenance （该应用是暂停维护了吗?）

### ISSUE THREAD

**Issue by YGXB-net** [NekoX-Dev/NekoX#1013]
我看最近的提交和 Actions 都已经是两个月之前了，Issue 回复也不及时了，作者好像这两个月也不活跃了，是出了什么事吗?

一定不要放弃这个项目呀，我用 NekoX 很久了，看到最近项目不活跃了就有点担心

**Comment by PLAYERUNKNOWNHatsune01** [comment]
I think it's dead fork now.

**Comment by KawaiiSh1zuku** [comment]
@PLAYERUNKNOWNHatsune01 no update no bug😇

**Comment by PLAYERUNKNOWNHatsune01** [comment]
> @PLAYERUNKNOWNHatsune01 no update no bug😇

No update no bugs. But has vulnerabilities and security holes lol.

**Comment by dic1911** [comment]
> > @PLAYERUNKNOWNHatsune01 no update no buginnocent
> 
> No update no bugs. But has vulnerabilities and security holes lol.

@PLAYERUNKNOWNHatsune01 How about you go merge the upstream changes and fix all the bugs instead of spitting shit here?

**Comment by PLAYERUNKNOWNHatsune01** [comment]
> > > @PLAYERUNKNOWNHatsune01 no update no buginnocent
> > 
> > 
> > No update no bugs. But has vulnerabilities and security holes lol.
> 
> @PLAYERUNKNOWNHatsune01 How about you go merge the upstream changes and fix all the bugs instead of spitting shit here?

How about you do that since that's your idea instead of crying (Gahh damn, another autistic edgy dev.) ?

**Comment by dic1911** [comment]
@PLAYERUNKNOWNHatsune01 Open your damn eyes and read, I'm not the one complaining shit, you are, either do something useful or shut up and fuck off.

**Comment by PLAYERUNKNOWNHatsune01** [comment]
> > > @PLAYERUNKNOWNHatsune01 no update no buginnocent
> > 
> > 
> > No update no bugs. But has vulnerabilities and security holes lol.
> 
> @PLAYERUNKNOWNHatsune01 How about you go merge the upstream changes and fix all the bugs instead of spitting shit here?

How about you do that since that's your idea instead of crying (Gahh damn, another autistic edgy dev.) ? 

> > > > @PLAYERUNKNOWNHatsune01 no update no buginnocent
> > > 
> > > 
> > > No update no bugs. But has vulnerabilities and security holes lol.
> > 
> > 
> > @PLAYERUNKNOWNHatsune01 How about you go merge the upstream changes and fix all the bugs instead of spitting shit here?
> 
> How about you do that since that's your idea instead of crying (Gahh damn, another autistic edgy dev.) ?

When did I complain? Anyway, I don't have time to fight with a autistic guy. So byeee, be safe, and seek help/medication you need.

**Comment by dic1911** [comment]
@PLAYERUNKNOWNHatsune01 

> When did I complain?

> has vulnerabilities and security holes lol.

LOL

**Comment by luvletter2333** [comment]
Stop leaving shit posts here. we may get back in next month
