### ISSUE TITLE
Theme resets every restart

### ISSUE THREAD

**Issue by HyperWinX** [NekoX-Dev/NekoX#1029]
**Describe the bug**
Selected theme resets to basic theme after NekoX restart, but custom theme is still selected. 

**To Reproduce**
Install custom theme
Close NekoX
Open, and you'll see basic theme
Open chat settings, and you'll see thats custom theme is selected

**Logcat**

**Expected behavior**
It's not supposed to reset theme every restart.

**Smartphone (please complete the following information):**
 - Device: Ulefone Armor 8 Pro
 - OS: Android 11
 - Version: NekoX version 9.3.3

**Comment by bakinazik** [comment]
Disable the auto night mod on the chat settings.
