### ISSUE TITLE
Neko is dead!

### ISSUE THREAD

**Issue by DeadSecTr** [NekoX-Dev/NekoX#1038]
Neko is dead folks! Dont expect any further updates from devs! Sorry...

**Comment by luvletter2333** [comment]
?

**Comment by y1111** [comment]
https://github.com/NekoX-Dev/NekoX/issues/1028#issuecomment-1935884462

neko is releasing whats seems like beta versions atualized more frequently in this tg group https://t.me/nekox_broken

i dont get why the mainteners just closed issue without explaining.
