### ISSUE TITLE
Add an option to bring back iOS emojis

### ISSUE THREAD

**Issue by JohnSmit268** [NekoX-Dev/NekoX#110]
I just found this app and it's great, but I would love the freedom of choice to bring back the default iOS emojis.
The twemojis look terrible compared to the iOS ones.

**Comment by nekohasekai** [comment]
Not Twemoji, now we use blob. As for free switching, there is no mature open source solution yet, so every time we add an option, it will be increased by 10m.

**Comment by JohnSmit268** [comment]
In that case is there any chance that we get different versions of neko with different emoji sets? Or any guide to compile one? I'm no dev but if there is a well described guide I'll try.

**Comment by nekohasekai** [comment]
Let's add some build types

**Comment by JohnSmit268** [comment]
Amazing, thank you very much, now let's try and learn the compiling of the apk😂
