### ISSUE TITLE
Importing Shadowsocks Configs From Clipboard

### ISSUE THREAD

**Issue by JohnSmit268** [NekoX-Dev/NekoX#112]
Can't import shadowsocks configs from clipboard.
Error: Unknown / Broken Link

1. Go to proxy manager
2. Copy a shadowsocks config to your clipboard
3. Hit the + sign and choose the import from clipboard option

Expected behavior:

Create a shadowsocks proxy from the clipboard config

Smartphone:
 - Device: [Samsung Galaxy A7 2018]
 - OS: [Android 10]
 - Version: [6.2.0.3-rc03]

**Comment by nekohasekai** [comment]
Check if you are using the mini version, or the required shadowsocks plugin is not installed.

**Comment by JohnSmit268** [comment]
I have the full release version installed.
There's shadowsocks proxies already configured and working.

**Comment by nekohasekai** [comment]
fixed

**Comment by JohnSmit268** [comment]
which brach is the commit on? I'm trying to compile the fixed version
