### ISSUE TITLE
Persian Jalali Date Picker

### ISSUE THREAD

**Issue by JohnSmit268** [NekoX-Dev/NekoX#116]
There's a growing community of Iranian people using Nekogram X.
A custom telegram date format (converted gregorian date to jalali date) matching the local Iran calendar would be an amazing addition.
This feature is requested by the Iranian Nekogram X community.
Here is a sample of a calendar switch button implemented in a closed source local unofficial telegram:

![IMG_20200715_235629_743](https://user-images.githubusercontent.com/16625616/87587593-85121d00-c6f7-11ea-8273-aa8d96fb6cbd.jpg)

**Comment by nekohasekai** [comment]
Now we need an Iranian calendar date picker with no external dependencies, because I am just an amateur developer :)

**Comment by JohnSmit268** [comment]
All you need is to convert the date telegram uses as it's current date to Iranian Jalali date and use that.
I did it with javascript before I can send you the library and usage guides if it helps

**Comment by nekohasekai** [comment]
This is easy, but the date picker is still displayed in the Gregorian calendar.

**Comment by JohnSmit268** [comment]
I might be able to find what you're looking for but I don't exactly know what the date picker is, could you elaborate?

**Comment by nekohasekai** [comment]
![Screenshot_2020-07-19-09-05-39-279_nekox messenger](https://user-images.githubusercontent.com/56506714/87864779-6fbf1c00-c99f-11ea-8291-ee1b3967589f.png)

**Comment by JohnSmit268** [comment]
Here, I found a few open source persian date pickers:
I recommend the first one as it's already in use in other local unofficial telegrams

https://github.com/mohamad-amin/PersianMaterialDateTimePicker

https://github.com/aliab/Persian-Date-Picker-Dialog

https://github.com/ali-sardari/PersianRangeDatePicker

https://github.com/alirezaafkar/SunDatePicker

**Comment by nekohasekai** [comment]
They all use very heavy app compat library, very old, none of them upgraded to androidx

**Comment by DearRude** [comment]
Any updates on this?

**Comment by JohnSmit268** [comment]
@DearRude There's no compatible AndroidX datepicker yet so no

**Comment by Navid83611** [comment]
no need to apply jalali calendar to the date picker.
what is important is that the jalali calendar is applied to the date bubble that appears on the chat screen.
you can note it under the option in neko settings if you want!
