### ISSUE TITLE
Apple emoji variant is missing some emojis

### ISSUE THREAD

**Issue by JohnSmit268** [NekoX-Dev/NekoX#136]
![20200810_174100](https://user-images.githubusercontent.com/16625616/89786172-c1873c00-db30-11ea-8c7d-2e99ac569139.jpg)
As you can see some of the emojis are missing and the default device emojis are being used instead.

**Comment by JohnSmit268** [comment]
![IMG_20200811_001427_056](https://user-images.githubusercontent.com/16625616/89824046-be5b7280-db67-11ea-97f2-9a1325345153.jpg)
Here is a more severe form of this bug.

**Comment by nekohasekai** [comment]
fixed
