### ISSUE TITLE
F-Droid?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [NekoX-Dev/NekoX#157]
Hello, have you guys thought of putting the FOSS version in F-Droid?

**Comment by fossdd** [comment]
There is an open [RFP](https://gitlab.com/fdroid/rfp/-/issues/1657) for the inclusion.

**Comment by TheEvilSkeleton** [comment]
@nekohasekai thank you so much! https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8476

**Comment by bingoxo** [comment]
why is the f-droid version many versions behind ?
