### ISSUE TITLE
self-destructive images aren't visible

### ISSUE THREAD

**Issue by srcurdy** [NekoX-Dev/NekoX#169]
When I try to visualize a self-destructive image there is a blur over the image and it is impossible to see.

Try to visualize a sent self-destructive image.

PS: I can't sent screenshots because this images can't be printed.

 - Device: Xiaomi Mi A3
 - OS: Android 10

**Comment by nekohasekai** [comment]
I think this is a network problem.

**Comment by srcurdy** [comment]
> I think this is a network problem.

No, it's happening with other peoples too.

**Comment by srcurdy** [comment]
> > I think this is a network problem.
> 
> No, it's happening with other peoples too.

**Comment by neekless** [comment]
Can confirm this bug exists. When destructive images are opened it just enlarges the blurred thumbnail and doesn't show the actual image. I can see them on telegram x fine.
