### ISSUE TITLE
Calling Crash & Proxy On Mini Versions Too

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [NekoX-Dev/NekoX#188]
**Describe the bug**
Nekogram crashes as soon as the call has been connected. And the mini version also has proxy which is redundent. There is full version for that.

**To Reproduce**
Just try to call a person by any means you will see it crashes

**Expected behavior**
Calling should work flawlessly and there shouldn't be any proxy on mini versions

**Screenshots**
Sorry can't perform at this moment

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - OS: Android 11

**Comment by accountForIssues** [comment]
I'd like to know this as well. I use mini (No GCM) version but I still see the proxy option (I know I can hide it). I also see multiple connections to fetch the proxy lists as per this [line](https://github.com/NekoX-Dev/NekoX/blob/58942794e3e0fb3e3d913bddc228c4a2109d9009/TMessagesProj/src/main/java/tw/nekomimi/nekogram/sub/SubManager.kt#L28).

I have not experienced any crashes but it seems redundant to fetch proxy lists and have the proxy option in the mini version as well. It would be ideal if the mini version could only contact TG servers and nothing else.

Is it possible to disable those checks and hide (if not remove) the proxy options by default in the mini version ?

@nekohasekai Any thoughts ?

**Comment by sudo-nautilus** [comment]
@accountForIssues I love the way that it pinged 世界 🏳️‍⚧️  on Telegram
