### ISSUE TITLE
Enable Translation Button For Single Message Selection

### ISSUE THREAD

**Issue by JohnSmit268** [NekoX-Dev/NekoX#200]
Currently upon selecting single messages the translate button does not appear on top.
It only appears for multi selected messages.
Enabling the button for single messages would help unify the translation UX.
![Screenshot_20201018-131854_Nekogram X](https://user-images.githubusercontent.com/16625616/96363962-a8a89180-1144-11eb-8468-246bd3ac41e4.jpg)
![Screenshot_20201018-132101_Nekogram X](https://user-images.githubusercontent.com/16625616/96363986-caa21400-1144-11eb-9247-5bcab39fba0a.jpg)

**Comment by nekohasekai** [comment]
Click -> Translate

**Comment by JohnSmit268** [comment]
I know that, I meant the top menu botton for the translation.
There's no reason to have it disabled for single selected messages.
