### ISSUE TITLE
No options to reactivate UID/DC display

### ISSUE THREAD

**Issue by adan89lion** [NekoX-Dev/NekoX#21]
#**Describe the bug**
Pre-release 6.0.1.14 disabled UID and DC by default, but there's no way to switch them back on.

**To Reproduce**
1. Update to 6.0.1.14
2. UID and DC is disabled by default (according to changelog)
3. Went to Neko Settings but there's no option to reactivate the display.

**Expected behavior**
Display UID and DC (for better group administrative purpose, a good and effective way to find out spam bots)

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20+
 - OS: Android 10
 - Version: OneUI 2.1

**Additional context**
n/a

**Comment by ygsk10** [comment]
go to /data/data/nekox.messager/shared_prefs/nekox_config.xml
add this between \<map> and \</map>
```
<boolean name="developer_mode" value="true" />
<boolean name="show_id_and_dc" value="true" />
```

**Comment by adan89lion** [comment]
@ygsk10 is there a non-root approach that could be implemented in the app?

**Comment by nekohasekai** [comment]
Moved into Neko Settings
