### ISSUE TITLE
Can't build the app

### ISSUE THREAD

**Issue by dadadani** [NekoX-Dev/NekoX#213]
**Describe the bug**
I tried following the instructions on the readme of this repo, and also on the repo of telegram-foss, but i can't still compile the app.

**Additional context**
Transform's input file does not exist: /home/daniele/src/NekoX/TMessagesProj/libs/ss-rust-release.aar. (See https://issuetracker.google.com/issues/158753935)
This also applies to every other submodules included by NekoX

**Comment by nekohasekai** [comment]
bin/native_libs.sh
bin/update_libs.sh

and build again 🤨

**Comment by dadadani** [comment]
Fixed by using the scripts mentioned.

Note: I needed to create a symbolic link on /opt/android-sdk because I wasn't able to use my directory con /home/USER
