### ISSUE TITLE
Blurry selfdestructive photos

### ISSUE THREAD

**Issue by neekless** [NekoX-Dev/NekoX#223]
**Describe the bug**
Selfdestructive photos sent to you by other people and/or selfdestructive photos you sent to other people using **a different client** will be blurry when opened on NekoX. A few people have mentioned this issue in the NekoX group as well as https://github.com/NekoX-Dev/NekoX/issues/169. I have done some investigation myself. Please don't close this issue dismissively.

**To Reproduce**
1. Either someone sends you a selfdestructive photo or you send someone else a selfdestructive photo using a different client (e.g. TelegramX)
2. Open the selfdestructive photo on NekoX

**Expected behavior**
This is a video of what happens in TelegramFOSS v7.1.3
![tgfoss](https://user-images.githubusercontent.com/22426822/97944963-113c7300-1dc1-11eb-941e-027952f17077.gif)

**Current behavior**
This is a video of what happens in NekoX v7.1.3.
![nekox](https://user-images.githubusercontent.com/22426822/97945102-7001ec80-1dc1-11eb-9b7a-1d66416be28c.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel2XL
 - OS: Android10
 - Version: 6.3.0.0-rc01 onwards

**Additional context**
To find out which version broke this, I went back and tested many versions. **Version 6.2.0.3-rc03 was the last working version.** From 6.3.0.0-rc01 onwards, selfdestructive photos have this problem. Also note that even in the bugged versions, if you use NekoX itself to send a selfdestructive photo to other people, it will open normally (probably due to cache or something). The commit difference between 6.2.0.3-rc03 and 6.3.0.0-rc01 is https://github.com/NekoX-Dev/NekoX/compare/v6.2.0.3-rc03...v6.3.0.0-rc01 though I'm unsure which is the exact commit that broke it. Please take this issue seriously as I cannot use newer versions of NekoX due to this issue.

**Comment by nekohasekai** [comment]
Thanks for your tests.

**Comment by neekless** [comment]
Verified fixed in 7.2.1-rc02 thanks!
