### ISSUE TITLE
Auto Update / Notification

### ISSUE THREAD

**Issue by anon97945** [NekoX-Dev/NekoX#227]
**Is your feature request related to a problem? Please describe.**
Going in to the channel and starting the update is like a workaround.

**Describe the solution you'd like**
A notification with buttons like "there is a new beta version install updates now".

**Comment by luvletter2333** [comment]
Added in [v7.7.2-1](https://github.com/NekoX-Dev/NekoX/releases/tag/v7.7.2-1).
