### ISSUE TITLE
Delete image files

### ISSUE THREAD

**Issue by Mk1378** [NekoX-Dev/NekoX#252]
**Describe the bug**
One should be able to delete image files from cache as well

**To Reproduce**
1. Go to Neko settings > Chat > Message menu 
2. Enable "delete downloaded file"
3. Tap on a message that has an image
4. You can't delete the image file

**Expected behavior**
Just like with videos and files, we should be able to delete downloaded image files as well

**Screenshots**
![Screenshot_20201117-062648_1](https://user-images.githubusercontent.com/46780868/99342769-d3038100-28a1-11eb-9dc4-8a3b3a7589cf.jpg)
![Screenshot_20201117-062714_1](https://user-images.githubusercontent.com/46780868/99342771-d4cd4480-28a1-11eb-80df-08450b76c47b.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei Y7
 - OS: Android 8
 - Version : Nekogram X v7.2.1-rc07-full-apple-emoji arm64-v8a releaseNoGcm
Lib v23, Core v4.32.1

**Comment by nekohasekai** [comment]
This also exists in the upstream, it seems that it is now changed to only the file cache can be cleaned
