### ISSUE TITLE
Save to chat folder

### ISSUE THREAD

**Issue by Mk1378** [NekoX-Dev/NekoX#257]
**Is your feature request related to a problem? Please describe.**

Currently the only way to save the files/videos/images, is to save them on the Downloads folder, which makes the folder very cluttered. 

**Describe the solution you'd like**

An option to save files of different chats in different locations, like this:

/storage/NekoX/[name of the chat]

**Comment by nekohasekai** [comment]
The telegram files do not have a field pointing to the chat

**Comment by Mk1378** [comment]
I don't think it's impossible though, it's been implemented by Bgram.

**Comment by nekohasekai** [comment]
Maybe you should ask them instead of me

**Comment by Mk1378** [comment]
OK, live long and prospect.
