### ISSUE TITLE
Two Questions & One Suggestion

### ISSUE THREAD

**Issue by if1y** [NekoX-Dev/NekoX#281]
**Two small questions hoping to be answered:**

1. Why would NekoX needs `Notification Access` when I tried to enable `Settings - Notifications and sounds - Keep-alive service'`? **I don't need to grant such permission with official client.**

2. What does `Settings - Neko Settings - General - Privacy - Disable system account` mean?

**One small suggesting:**

Now that we have `Disable Proxy when VPN enabled`, can we **enable proxy when vpn disabled (or unable to access the server)**?

---

Thank you.

**Comment by nekohasekai** [comment]
> Why would NekoX needs Notification Access when I tried to enable Settings - Notifications and sounds - Keep-alive service' ?

用于在没有 fcm 时稳定推送通知 (https://github.com/NekoX-Dev/NekoX/blob/dev/TMessagesProj/src/main/java/tw/nekomimi/nekogram/NekoXPushService.kt), 我计划移除此, 由于永远运行导致了大量耗电以及放大了内存泄漏.

它不会阅读您的通知, 而是保持推送服务稳定运行, 如果您不启用此, 本软件将拉起一个前台通知 (关闭后不影响推送).

> What does Settings - Neko Settings - General - Privacy - Disable system account mean?

即系统设置中的 `帐号`, Telegram Android 不使用 Android 的帐号系统存储凭据, 也不使用同步服务, 但默认将您的用户ID存储到系统中, NekoX 将它更改为您的名称并允许关闭.

> Enable proxy when vpn disabled

TODO

**Comment by if1y** [comment]
Hi, I just suffered sone connection issue.

With proxy on, and already added whiltelist in memory cleaner, it is **unable to receive msg unless opening the App in the foreground**.

Just tried enable `Keep-alive service` and `Background Connection` (totally the same settings as the official App) , but still fail to.
