### ISSUE TITLE
NekoX noGsm runs in background when notification service is disabled

### ISSUE THREAD

**Issue by amir28** [NekoX-Dev/NekoX#285]
**Describe the bug**
Hi, In noGSM version disabling notification service works but it still runs in background

**To Reproduce**
1. Install lastest noGSM version
2. Go to Settings -> Notifications and Sounds 
3. Scroll down and turn 'Background Connection' option off

**Logcat**
First I cleared logs and turn 'Background Connection' on and off. Here is log:
--------- beginning of main
12-10 20:22:29.590  4781  4781 I chatty  : uid=10248(nekox.messenger) expire 12 lines
12-10 20:22:29.915  4781  4841 I chatty  : uid=10248(nekox.messenger) expire 2 lines
12-10 20:22:30.177  4781  4819 I chatty  : uid=10248(nekox.messenger) DefaultDispatch expire 3 lines
12-10 20:22:30.642  4781  4829 I chatty  : uid=10248(nekox.messenger) Thread-17 expire 12 lines
12-10 20:22:30.643  4781  4822 I chatty  : uid=10248(nekox.messenger) stageQueue expire 22 lines
12-10 20:22:30.889  4781  5102 I chatty  : uid=10248(nekox.messenger) DefaultDispatch expire 4 lines
12-10 20:22:33.517  4781  4814 I chatty  : uid=10248(nekox.messenger) RenderThread expire 1 line
12-10 20:23:01.602  4781  4829 I chatty  : uid=10248(nekox.messenger) Thread-17 expire 3 lines
12-10 20:23:17.955  4781  4808 I chatty  : uid=10248(nekox.messenger) fileUploadQueue expire 2 lines
12-10 20:23:17.956  4781  4809 I chatty  : uid=10248(nekox.messenger) storageQueue expire 3 lines
12-10 20:23:18.058  4781  4781 I chatty  : uid=10248(nekox.messenger) expire 7 lines
12-10 20:23:18.072  4781  4809 I chatty  : uid=10248(nekox.messenger) storageQueue expire 4 lines
12-10 20:23:18.124  4781  4781 I chatty  : uid=10248(nekox.messenger) expire 1 line
12-10 20:23:18.221  4781  4808 I chatty  : uid=10248(nekox.messenger) fileUploadQueue expire 2 lines
12-10 20:23:18.222  4781  5102 I chatty  : uid=10248(nekox.messenger) DefaultDispatch expire 1 line
12-10 20:23:18.223  4781  4808 I chatty  : uid=10248(nekox.messenger) fileUploadQueue expire 2 lines
12-10 20:23:18.224  4781  4819 I chatty  : uid=10248(nekox.messenger) DefaultDispatch expire 1 line
12-10 20:23:18.225  4781  4808 I chatty  : uid=10248(nekox.messenger) fileUploadQueue expire 2 lines
12-10 20:23:18.300  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_userFull@e12064e error = null
12-10 20:23:18.302  4781  4781 D FileLog : peer settings loaded for 449384375 add = false block = false spam = false share = false geo = false hide = true distance = 0
12-10 20:23:18.965  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_photos_photos@a2fe97b error = null
12-10 20:23:18.967  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/455032763_330338.jpg
12-10 20:23:18.968  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/434314635_173846.jpg
12-10 20:23:18.968  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg
12-10 20:23:19.504  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_photos_photos@fac1398 error = null
12-10 20:23:19.506  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/455032763_330338.jpg
12-10 20:23:19.507  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/434314635_173846.jpg
12-10 20:23:19.507  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg
12-10 20:23:30.265  4781  5102 D FileLog : send request TLRPC$TL_account_updateStatus with token = 342
12-10 20:23:31.031  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_boolFalse@9ccd7f1 error = null
12-10 20:23:31.755  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@b698fd6
12-10 20:23:31.756  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@b49a257
12-10 20:23:34.521  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@41ad144
12-10 20:23:34.522  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateUserStatus@9c6022d
12-10 20:23:34.525  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg
12-10 20:23:40.273  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@9c6d362
12-10 20:23:40.274  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@ddc0cf3
12-10 20:23:40.275  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@995bdb0
12-10 20:23:40.275  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@aad9429
12-10 20:24:00.060  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@fc2c3ae
12-10 20:24:00.060  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@420854f
12-10 20:24:00.060  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@49104dc
12-10 20:24:00.061  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@f6249e5
12-10 20:24:00.062  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@b7b6cba
12-10 20:24:00.063  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@8a276b
12-10 20:24:19.925  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates@a9792c8
12-10 20:24:19.925  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates@ff29f61
12-10 20:24:19.927  4781  4822 D FileLog : org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@ce39a86 need get channel diff, pts: 1598788 1598790 count = 1 channelId = 1077131949
12-10 20:24:19.927  4781  4822 D FileLog : add to queue
12-10 20:24:19.928  4781  4822 D FileLog : HOLE IN CHANNEL 1077131949 UPDATES QUEUE - will wait more time
12-10 20:24:19.929  4781  4822 D FileLog : org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@fa1cf47 need get channel diff, pts: 1598788 1598791 count = 1 channelId = 1077131949
12-10 20:24:19.929  4781  4822 D FileLog : add to queue
12-10 20:24:19.929  4781  4822 D FileLog : HOLE IN CHANNEL 1077131949 UPDATES QUEUE - will wait more time
12-10 20:24:21.931  4781  4822 D FileLog : QUEUE CHANNEL 1077131949 UPDATES WAIT TIMEOUT - CHECK QUEUE
12-10 20:24:21.931  4781  4822 D FileLog : HOLE IN CHANNEL 1077131949 UPDATES QUEUE - getChannelDifference 
12-10 20:24:21.932  4781  4822 D FileLog : start getChannelDifference with pts = 1598788 channelId = 1077131949
12-10 20:24:21.933  4781  5043 D FileLog : send request TLRPC$TL_updates_getChannelDifference with token = 343
12-10 20:24:22.801  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates_channelDifference@cf71374 error = null
12-10 20:24:22.861  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@cd8d09d
12-10 20:24:22.862  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@e4ed912
12-10 20:24:22.863  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@3a218e3
12-10 20:24:22.868  4781  4822 D FileLog : received channel difference with pts = 1598791 channelId = 1077131949
12-10 20:24:22.868  4781  4822 D FileLog : new_messages = 0 messages = 0 users = 1 chats = 1 other updates = 3
12-10 20:24:26.808  4781  5102 D FileLog : send request TLRPC$TL_account_updateStatus with token = 344
12-10 20:24:27.773  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@22bf2e0
12-10 20:24:27.775  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@9f6d999
12-10 20:24:27.801  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_boolFalse@9bd745e error = null
12-10 20:24:38.709  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates@dd3603f
12-10 20:24:38.709  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates@a0d5d0c
12-10 20:24:38.713  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateNewChannelMessage@d527655
12-10 20:24:38.714  4781  4822 D FileLog : org.telegram.tgnet.TLRPC$TL_updateNewChannelMessage@d527655 channelId = 1335677286
12-10 20:24:38.715  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg
12-10 20:24:38.717  4781  4822 D FileLog : org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@6e8786a need get channel diff, pts: 1598791 1598793 count = 1 channelId = 1077131949
12-10 20:24:38.717  4781  4822 D FileLog : add to queue
12-10 20:24:38.718  4781  4822 D FileLog : HOLE IN CHANNEL 1077131949 UPDATES QUEUE - will wait more time
12-10 20:24:38.727  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg
12-10 20:24:40.509  4781  4822 D FileLog : QUEUE CHANNEL 1077131949 UPDATES WAIT TIMEOUT - CHECK QUEUE
12-10 20:24:40.510  4781  4822 D FileLog : HOLE IN CHANNEL 1077131949 UPDATES QUEUE - getChannelDifference 
12-10 20:24:40.510  4781  4822 D FileLog : start getChannelDifference with pts = 1598791 channelId = 1077131949
12-10 20:24:40.511  4781  5043 D FileLog : send request TLRPC$TL_updates_getChannelDifference with token = 345
12-10 20:24:41.258  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@ba811e9
12-10 20:24:41.259  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@f3ace6e
12-10 20:24:41.287  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates_channelDifference@e03990f error = null
12-10 20:24:41.313  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@c4ed9c
12-10 20:24:41.314  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@6e6e3a5
12-10 20:24:41.318  4781  4822 D FileLog : received channel difference with pts = 1598793 channelId = 1077131949
12-10 20:24:41.318  4781  4822 D FileLog : new_messages = 0 messages = 0 users = 1 chats = 1 other updates = 2
12-10 20:24:59.100  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@49637a
12-10 20:24:59.101  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@5eab72b
12-10 20:24:59.101  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@f014788
12-10 20:24:59.101  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@2871521
12-10 20:24:59.101  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@47a3d46
12-10 20:24:59.102  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@db9b07
12-10 20:24:59.102  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@5275434
12-10 20:24:59.103  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@19ee25d
12-10 20:25:04.000  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@a8ce7d2
12-10 20:25:04.000  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates@b0ce0a3
12-10 20:25:04.001  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@1ff7fa0
12-10 20:25:04.001  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateUserStatus@86c4759
12-10 20:25:04.005  4781  4822 D FileLog : org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@badaf1e need get channel diff, pts: 1598793 1598796 count = 1 channelId = 1077131949
12-10 20:25:04.005  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg
12-10 20:25:04.006  4781  4822 D FileLog : add to queue
12-10 20:25:04.006  4781  4822 D FileLog : HOLE IN CHANNEL 1077131949 UPDATES QUEUE - will wait more time
12-10 20:25:04.007  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateMessagePoll@382e3ff
12-10 20:25:04.008  4781  4822 D FileLog : HOLE IN CHANNEL 1077131949 UPDATES QUEUE - will wait more time
12-10 20:25:06.006  4781  4822 D FileLog : QUEUE CHANNEL 1077131949 UPDATES WAIT TIMEOUT - CHECK QUEUE
12-10 20:25:06.007  4781  4822 D FileLog : HOLE IN CHANNEL 1077131949 UPDATES QUEUE - getChannelDifference 
12-10 20:25:06.007  4781  4822 D FileLog : start getChannelDifference with pts = 1598793 channelId = 1077131949
12-10 20:25:06.008  4781  5102 D FileLog : send request TLRPC$TL_updates_getChannelDifference with token = 346
12-10 20:25:06.778  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates_channelDifference@66cf5cc error = null
12-10 20:25:06.823  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@7110015
12-10 20:25:06.824  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@5819f2a
12-10 20:25:06.826  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@b2bc11b
12-10 20:25:06.828  4781  4822 D FileLog : received channel difference with pts = 1598796 channelId = 1077131949
12-10 20:25:06.828  4781  4822 D FileLog : new_messages = 0 messages = 0 users = 1 chats = 1 other updates = 3
12-10 20:25:08.785  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg
12-10 20:25:14.548  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@1a2caef
12-10 20:25:14.549  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates@fff69fc
12-10 20:25:14.550  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateUserStatus@6f31885
12-10 20:25:14.552  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@2d826da
12-10 20:25:14.554  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg
12-10 20:25:18.319  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates@33328e7
12-10 20:25:18.320  4781  4822 D FileLog : org.telegram.tgnet.TLRPC$TL_updateNewChannelMessage@ce8fc94 need get channel diff, pts: 26830 26832 count = 1 channelId = 1448468278
12-10 20:25:18.320  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates@aa0d33d
12-10 20:25:18.320  4781  4822 D FileLog : add to queue
12-10 20:25:18.320  4781  4822 D FileLog : HOLE IN CHANNEL 1448468278 UPDATES QUEUE - will wait more time
12-10 20:25:18.321  4781  4822 D FileLog : org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@504b732 need get channel diff, pts: 82286 82288 count = 1 channelId = 1011631274
12-10 20:25:18.321  4781  4822 D FileLog : add to queue
12-10 20:25:18.323  4781  4822 D FileLog : HOLE IN CHANNEL 1011631274 UPDATES QUEUE - will wait more time
12-10 20:25:18.324  4781  4822 D FileLog : HOLE IN CHANNEL 1448468278 UPDATES QUEUE - will wait more time
12-10 20:25:20.323  4781  4822 D FileLog : QUEUE CHANNEL 1011631274 UPDATES WAIT TIMEOUT - CHECK QUEUE
12-10 20:25:20.323  4781  4822 D FileLog : HOLE IN CHANNEL 1011631274 UPDATES QUEUE - getChannelDifference 
12-10 20:25:20.324  4781  4822 D FileLog : start getChannelDifference with pts = 82286 channelId = 1011631274
12-10 20:25:20.325  4781  5102 D FileLog : send request TLRPC$TL_updates_getChannelDifference with token = 347
12-10 20:25:20.329  4781  4822 D FileLog : QUEUE CHANNEL 1448468278 UPDATES WAIT TIMEOUT - CHECK QUEUE
12-10 20:25:20.329  4781  4822 D FileLog : HOLE IN CHANNEL 1448468278 UPDATES QUEUE - getChannelDifference 
12-10 20:25:20.330  4781  4822 D FileLog : start getChannelDifference with pts = 26830 channelId = 1448468278
12-10 20:25:20.331  4781  5043 D FileLog : send request TLRPC$TL_updates_getChannelDifference with token = 348
12-10 20:25:21.086  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates_channelDifference@57f6c83 error = null
12-10 20:25:21.116  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@aa34e00
12-10 20:25:21.117  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@d4c6639
12-10 20:25:21.121  4781  4822 D FileLog : received channel difference with pts = 82288 channelId = 1011631274
12-10 20:25:21.122  4781  4822 D FileLog : new_messages = 0 messages = 0 users = 1 chats = 1 other updates = 2
12-10 20:25:21.306  4781  5043 D FileLog : send request TLRPC$TL_account_getContactSignUpNotification with token = 349
12-10 20:25:21.642  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updates_channelDifference@c5d0d90 error = null
12-10 20:25:21.697  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateEditChannelMessage@b20d689
12-10 20:25:21.697  4781  4822 D FileLog : received channel difference with pts = 26832 channelId = 1448468278
12-10 20:25:21.698  4781  4822 D FileLog : new_messages = 1 messages = 0 users = 1 chats = 1 other updates = 1
12-10 20:25:22.454  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_boolFalse@cce6976 error = null
12-10 20:25:23.458  4781  5043 D FileLog : send request TLRPC$TL_account_updateStatus with token = 350
12-10 20:25:24.225  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_boolFalse@53ff26f error = null
12-10 20:25:25.193  4781  4829 D FileLog : java received org.telegram.tgnet.TLRPC$TL_updateShort@8f23b7c
12-10 20:25:25.195  4781  4822 D FileLog : process update org.telegram.tgnet.TLRPC$TL_updateChannelMessageViews@b2b4c05
12-10 20:25:25.196  4781  4822 D FileLog : org.telegram.tgnet.TLRPC$TL_updateChannelMessageViews@b2b4c05 channelId = 1011631274
12-10 20:25:31.227  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg
12-10 20:25:31.425  4781  4808 D FileLog : finished downloading file to /storage/emulated/0/Android/data/nekox.messenger/files/caches/464928268_107188.jpg

**Expected behavior**
I was expected when NekoX is closed it don't running in background.

**Smartphone (please complete the following information):**
 - Device: Nokia 2.1
 - OS: Android 10 go edition
 - Version: v7.2.1-rc07-mini armebi-v7a releaseNoGsm

Thanks a lot and sorry for my grammars mistaks

**Comment by nekohasekai** [comment]
You should also disable "Background Connection" and force restart the app
