### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by cdmullins69** [NekoX-Dev/NekoX#292]
**Describe the bug**

**To Reproduce**

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: [e.g. Android8.1]
 - Version [e.g. 5.15.0]

**Additional context**

**Comment by neekless** [comment]
this is the second issue you've opened with absolutely no information. are you a bot?

**Comment by cdmullins69** [comment]
No, I'm sorry
