### ISSUE TITLE
Forced close when trying to open the side menu on Android 4.4.2

### ISSUE THREAD

**Issue by AlbahrawyAlalimi** [NekoX-Dev/NekoX#300]
Telegram crashes when I try to open the side menu, either by dragging or by clicking on the three dashes above, and therefore I cannot access the Telegram settings. This problem also exists in the official version of Telegram. I hope the problem will be solved soon, thank you

**Comment by nekohasekai** [comment]
I did not reproduce this problem on the 4.4.2 android emulator. What is your device?

**Comment by AlbahrawyAlalimi** [comment]
I am running it on Huawei y336-u02 phone

**Comment by AlbahrawyAlalimi** [comment]
I am using version 7.0.1 and it does not have this problem, this problem appeared since version 7.1.0
