### ISSUE TITLE
Default tab when "Hide All Chats tab" is enabled

### ISSUE THREAD

**Issue by neekless** [NekoX-Dev/NekoX#306]
**Describe the bug**
In 7.2, when "Hide All Chats tab" is enabled, closing and opening the app will show the first folder by default instead of All Chats. 

In 7.3, when "Hide All Chats tab" is enabled, closing and opening the app will show All Chats by default. Only after swiping to another folder and swiping back will it show the first folder. 

**To Reproduce**
1. Enable "Hide All Chats tab". 
2. Exit the app. Clear it from recent apps. 
3. Launch the app. 
4. All Chats are shown even though the tab title is the first folder's name. 

**Expected behavior**
When "Hide All Chats tab" is enabled, closing and opening the app will show the first folder by default instead of All Chats. 

**Screenshots**
This is how it should be, also this is the behavior in 7.2
![Screenshot_20201228-102321_Trebuchet](https://user-images.githubusercontent.com/22426822/103185395-36e48500-48f7-11eb-8c7c-94c9a978f241.png)

This is how it is in 7.3. Note the tab title. 
![Screenshot_20201228-102315_Trebuchet](https://user-images.githubusercontent.com/22426822/103185377-26340f00-48f7-11eb-8757-eda42de37c4f.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 xl
 - OS: Android 11
 - Version: Nekogram X v7.3.1-rc01-mini-no-emoji arm64-v8a release

**Additional context**

**Comment by LoneDev6** [comment]
Why was this closed?
I can still reproduce that issue on Neko X 9.1.6
