### ISSUE TITLE
Might need improvement of build-in DNS

### ISSUE THREAD

**Issue by if1y** [NekoX-Dev/NekoX#313]
**Connection is too slow, especially with build-in proxy. Even lost message when the app is in the background.**

I tried to catch network packages and found NekoX keeps querying `dns.twnic.tw`.
My proxy server is beyond of Taiwan, and there're huge delay between them (~300ms).

And I found it indeed in the source code:
https://github.com/NekoX-Dev/NekoX/blob/98de89ebf6240e56101447c3de107a306b78a579/TMessagesProj/src/main/java/tw/nekomimi/nekogram/utils/DnsFactory.kt#L28

**Should be the problem of this DNS server I think.**
**Using DNS servers with local CDN might be better?**

**Comment by nekohasekai** [comment]
The connection to telegram server uses the ip directly, and the client does not use these DNS to send http requests, they are only used to query the update of the telegram servers.

**Comment by if1y** [comment]
But the network packages indeed show it keeps querying the DNS.

Maybe this is the other problem...
Just my personal guess...

**Comment by nekohasekai** [comment]
If you block, otherwise it will not request all servers, usually done at https://mozilla.cloudflare-dns.com/dns-query

**Comment by if1y** [comment]
Seems solved when I change the domain of MTProxy into its IP address
