### ISSUE TITLE
[Feature Request] Add Ghost/Stealth Mode

### ISSUE THREAD

**Issue by shah-95** [NekoX-Dev/NekoX#320]
Can I request to add the ghost mode feature (people can't see your online status in chats/groups and double ticks in chats/secret chats etc) as in mobogram and some other clients.

Thankyou so much for your efforts !

**Comment by nekohasekai** [comment]
Telegram does not allow it, even if there are no consequences.

**Comment by shah-95** [comment]
Thanks for the response Sir.

But do you mean telegram's TOS does not allow it ? Or you mean its not possible on software side ? Or both ? Because some other unofficial clients already have that option .. so I don't think telegram would take any action against your custom client only ?

Yours is really great one, I just want it to have every other of those features that those clients already have to make it the best 👍 

And ofcourse I understand if you don't want to do this.. but as I read its just fiddling around settings already present in telegram i.e enabling somebmessage previews feature permanently and hiding presence continously through some code etc. Probably you already know :p

**Comment by shenef** [comment]
Per the Telegram API Terms of Service adding a Ghost mode is not allowed.
https://core.telegram.org/api/terms
While there usually is no action from telegram, they might take action at any time and remove the API access and request the removal of the app from the google play store. There have been instances of this happening in the past.
