### ISSUE TITLE
Cant delete multiple messages

### ISSUE THREAD

**Issue by alefvanoon** [NekoX-Dev/NekoX#328]
![image](https://user-images.githubusercontent.com/53198048/104108531-a59fe600-52da-11eb-8f32-b1a8c20f2756.png)

**Comment by frknkrc44** [comment]
Use this
![Screenshot_20210110-024244](https://user-images.githubusercontent.com/45714956/104110923-8a8aa180-52ed-11eb-9a75-cead5d7cc64d.png)
