### ISSUE TITLE
trojan添加sni标识的建议

### ISSUE THREAD

**Issue by pudding1111** [NekoX-Dev/NekoX#330]
你好，开发者
trojan代理一般由服务器地址、端口、密码，域名sni四个部分组成，本软件的trojan设置项里面没有sni添加位置，如果 服务器地址、端口经过中转，没有sni则无法正常使用trojan代理。
所以，建议开发者在trojan代理中添加对sni的支持。

**Comment by pudding1111** [comment]
咳咳，开发者都修了trojan的问题了，我能不能在过分一点？比如说，添加对机场订阅的支持和批量ping功能？？

**Comment by nekohasekai** [comment]
订阅已经有了，仔细看。批量ping的话，也是有的，但是有一些问题。
