### ISSUE TITLE
Missing clear history in dm

### ISSUE THREAD

**Issue by anon97945** [NekoX-Dev/NekoX#404]
**Describe the bug**
Since the update of the self-destructive timer in dm, the clear history button is gone.

**Screenshots**
![Screenshot_20210309-155409_Nekogram_X](https://user-images.githubusercontent.com/54719502/110489670-da1ffa80-80ef-11eb-9e71-d7162059421d.png)

Nekogram X v7.5.0-rc04-mini arm64-v8a releaseNoGcm

**Comment by anon97945** [comment]
Fixed in non secret chats but still missing in secret chats.

**Comment by ilyabemola** [comment]
Install RC11 bro

**Comment by anon97945** [comment]
> Install RC11 bro

i have and im not your bro. thx.

Its fixed in RC12, but now we have "set auto-delete timer" in secret chat, which actually does not work since secret chat uses the "Set self destruct-timer". So the "set auto-delete timer" should be removed from secret chats menu.
