### ISSUE TITLE
Ignore blocked user in group

### ISSUE THREAD

**Issue by davidj77** [NekoX-Dev/NekoX#416]
Hi developer
It would be great if you add the "ignore blocked user in group" again
Maybe it seems a non useful feature, but for many user of your app it has importance, because some people in groups sometimes send messages that are offensive for other people but Admins doesn't bans them.

So with this feature we don't need to continue seeing messages that are offensive for us.

This feature add difference to NekoX among Telegram third part clients.

Thanks in advance

**Comment by EduFrazao** [comment]
This is a REALLY nice feature..Why this request is closed almost immediatelly?
