### ISSUE TITLE
GIF查看改进

### ISSUE THREAD

**Issue by redaiert2** [NekoX-Dev/NekoX#458]
希望查看GIF可以像Telegram X那样显示整个图片（视频？）的长度（传到Telegram云端的GIF都会被转换成MP4格式吧？）
具体如图所示。
![Screenshot_20210405-133834](https://user-images.githubusercontent.com/26710960/113541266-72889c80-9614-11eb-949f-967d15b9b722.jpg)

**Comment by luvletter2333** [comment]
Already implemented

**Comment by redaiert2** [comment]
这个功能是不是失效了？

在9.3.3版本下，即使打开了“GIF显示为视频”选项，打开GIF图片也不会显示进度条。
![Screenshot_20230826_210958](https://github.com/NekoX-Dev/NekoX/assets/26710960/28e3d652-7398-400d-b5d1-e74271d47e7d)
![Screenshot_20230826_211211](https://github.com/NekoX-Dev/NekoX/assets/26710960/4b1d6872-6833-4c2a-abfc-b24b53e1b90e)
