### ISSUE TITLE
Use updated fork of SSE2NEON

### ISSUE THREAD

**Issue by jserv** [NekoX-Dev/NekoX#46]
[DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon) is arguably the most active fork of existing SSE2NEON derived projects. At present, this repository contains an old copy of SSE2NEON. Would it make sense to switch to [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon)?

**Comment by nekohasekai** [comment]
No, I think. It's the code for video calls that tg doesn't yet support.
