### ISSUE TITLE
Settings Backup 

### ISSUE THREAD

**Issue by saipraveenbammidi** [NekoX-Dev/NekoX#467]
**Is your feature request related to a problem? Please describe.**
I install custom roms usually,So when I install neko x and login, I get frustrated to set the every setting I need every time after I install the app.

**Describe the solution you'd like**
I'd like to suggest a feature in which there should be a option to backup all the settings like font size, in app vibration etcetera, as seen in some other client of telegram.

**Comment by nekohasekai** [comment]
Maybe you can try [oandbackupx](https://github.com/machiav3lli/oandbackupx).

**Comment by saipraveenbammidi** [comment]
> Maybe you can try [oandbackupx](https://github.com/machiav3lli/oandbackupx).

Yeah, I know oandbackupx , but I only need a option in neko x if backuping up all the settings, Thank you anyways.
