### ISSUE TITLE
Crash and jump out app when open

### ISSUE THREAD

**Issue by sbbnm** [NekoX-Dev/NekoX#470]
Hi
Jump out and crash on version 7.7.2 on android 4.4 redmi note 4g 
İ cant sent bug report because of jump out from app 
upload a logcat file
[logcat.txt](https://github.com/NekoX-Dev/NekoX/files/6372160/logcat.txt)

**Comment by sbbnm** [comment]
here is logcat
https://github.com/NekoX-Dev/NekoX/files/6372160/logcat.txt

**Comment by DarknessKiller123** [comment]
Same for me. I'm on Android 11.

**Comment by foldfree** [comment]
Same here on arrowOS, android 11 - redmi note 8
And  lineageOS - android 10 - galaxy S2
With the f-droid builds
