### ISSUE TITLE
1)On group menu add option to see only admins (like in plus)
2) add no quotes forward next to the forward as shown below
3)add some good icons like below 
@admin


### ISSUE THREAD

**Issue by Yaswanthroy** [NekoX-Dev/NekoX#471]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![IMG_20210420_174517_862.jpg](https://user-images.githubusercontent.com/37733281/115394349-53872e80-a200-11eb-9b1f-ccc9e057ca5d.jpg)
![Screenshot_20210420-174702_Nekogram_X.png](https://user-images.githubusercontent.com/37733281/115394577-89c4ae00-a200-11eb-8e14-52f6eb1ebc1a.png)

**Comment by Navid14101** [comment]
@Yaswanthroy :/

**Comment by Yaswanthroy** [comment]
> @Yaswanthroy :/

I haven't asked fancy things 
1)On group menu add option to see only admins 
2) add no quotes forward next to the forward 
3)add some good icons for title
These are must have features for me

**Comment by Yaswanthroy** [comment]
> @Yaswanthroy :/
I hope at least he fix this and add some good icons
![Screenshot_20210420-174702_Nekogram_X.png](https://user-images.githubusercontent.com/37733281/115399332-b3cc9f00-a205-11eb-8109-54164d3b6d76.png)
