### ISSUE TITLE
1)On group menu add option to see only admins (if possible)
2) add no quotes forward next to the forward( it's help to forward much faster)
3)add some good icons for title(bot emoji was not there) 
Any least add anyone of the feature 
Thank you

### ISSUE THREAD

**Issue by Yaswanthroy** [NekoX-Dev/NekoX#472]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20210420-182437_Nekogram_X.png](https://user-images.githubusercontent.com/37733281/115399784-2dfd2380-a206-11eb-917d-51bbc81b7a01.png)

**Comment by Navid14101** [comment]
nekox already has an option to see only admins.
just tap on pencil icon in the group info.

**Comment by Yaswanthroy** [comment]
> nekox already has an option to see only admins.
> just tap on pencil icon in the group info.

Thanks
What about other features
