### ISSUE TITLE
Go to first message.

### ISSUE THREAD

**Issue by saipraveenbammidi** [NekoX-Dev/NekoX#473]
Well, I always receive messages from new users as the work I deal with include interacting with new people daily. After a conversation is completed, they may ping me again after somedays, As I am not used to save everyone phone number and due to privacy settings, It would be good If we have dedicated option in 3 dot menu in a particular chat saying 'Go to first message'.So we can know the person who that may be in a faster way.

Adding a dedicated option in 3dot menu in conversation chat saying ' Go to first message'.

There is no particular alternative source or feature respectively for this.

**Comment by luvletter2333** [comment]
Added in 7.7.2-1, but it’s located in Search
