### ISSUE TITLE
Button on chat to redirect to channel

### ISSUE THREAD

**Issue by CoolGuyMK** [NekoX-Dev/NekoX#478]
Hi,
Could u add a button on the chat (like the one on the channel when it's linked to a chat) to redirect to the linked channel?

**Comment by luvletter2333** [comment]
This feature is present in the official Telegram.

You can click on the avatar of the message posted by the channel to jump to it.

**Comment by CoolGuyMK** [comment]
> This feature is present in the official Telegram.
> 
> You can click on the avatar of the message posted by the channel to jump to it.

I mean something like this

![fotor_1619555754701~2](https://user-images.githubusercontent.com/63323163/116309639-4abacd80-a7a9-11eb-9be5-fe43845868ef.jpg)

As u can see in this image this is a channel and there is a button to redirect to chat 
The feature i want is same as channel but instead a button on chat to redirect to (linked) channel

I hope u get me now :)
