### ISSUE TITLE
Problem with Notification channel 

### ISSUE THREAD

**Issue by terrytw** [NekoX-Dev/NekoX#484]
Hi, thank devs for this project, thank you for all your hard work.

I have discovered a problems with notification channel. Notification channels are not named correctly. If you go to NekoX's android notification setting, you will see a lot of channels, all named "default"

Some of them are group chats, some are private chats, some are subscribed channels, however they are all named default, which makes them indistinguishable. 

Also there is a "internal notification" category which is not translated.

**Comment by Xi-PP** [comment]
Because all of those notifications are handled in the app
Open info[chnl, group, user, bot] whoever you want. Then tap on notifications & choose customize
Check..👇🏻
![IMG_20210427_174214](https://user-images.githubusercontent.com/77042574/116239234-0961f800-a780-11eb-9025-9f4472719307.jpg)

The settings in system is Default notifications for [group, chnl, private] and it's good

**Comment by terrytw** [comment]
Thanks for the heads up, I do know that there are multiple ways to customize to notification in the app. 

It still does not change the fact that in Android system setting, they are not named correctly. System setting is the universal way of controlling notification, for example I can long press on pull down notification to open setting, that is the way it is intended to be used. 

Also, there is a feature called "override do not disturb", for example when my phone is in do not disturb mode, I want every other notification to be muted, except for Telegram private chat. Apps do not have the permission to control that setting. You can only use system setting for that function.

**Comment by tiagogaspar8** [comment]
I would love to see this fixed upstream but it seems no one is aware of this/cares.
Is there anything I can do to help? To get this fixed and merged upstream? I don't know how to code otherwise I'd do it
