### ISSUE TITLE
Add a "beginning" button in the chat search calander menu

### ISSUE THREAD

**Issue by otakuashwin** [NekoX-Dev/NekoX#487]
There is a very cool feature in the telegram x is that when we search for chats or post in the group/channel by dates, there is a "beginning" button in the calender section and clicking on that pushes us to the first message sent in the group/channel.

And why that? We can know the release date of the channels and groups. We can find out the day when the group started, the first convo.

I have attached a screenshot for the reference, thanks for reading :)
![IMG_20210429_074832_894](https://user-images.githubusercontent.com/66071679/116494856-5ac4d100-a8bf-11eb-9456-0d99a128eff9.jpg)

**Comment by luvletter2333** [comment]
Add in 1c6a86b1
