### ISSUE TITLE
unable to import Clash subscription url!

### ISSUE THREAD

**Issue by Kookemoon** [NekoX-Dev/NekoX#492]
**Describe the bug**
I can not import this Clash subscription Url:
https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet.yml
but,that subscriptionurl has no problem with "Clash For Android"!

**To Reproduce**

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**

**Screenshots**
![Screenshot_20210501-140707_Nekogram X](https://user-images.githubusercontent.com/83494123/116778344-99f14e80-aa86-11eb-9486-527845560bf3.jpg)

**Smartphone (please complete the following information):**
 - Device: SM-A715F/DS
 - OS: Android 11
 - Version 7.2.2 Arm64v8

**Additional context**

**Comment by luvletter2333** [comment]
Fix 33e83cae
