### ISSUE TITLE
Closes immediately after launch

### ISSUE THREAD

**Issue by A7355608** [NekoX-Dev/NekoX#495]
Application closes immediately after launch with no error message in UI. Log with error, warn, debug attached. I tried to give permissions before launching but I don't think I can affect the phone state permission for "ro.serialno". What else can I try? 

This is a fresh installation of NekoX 7.7.2-armeabi-v7a from F-droid. 

LG LM-Q730TM 
Android 10

[neko-dbg.log](https://github.com/NekoX-Dev/NekoX/files/6410851/neko-dbg.log)

**Comment by luvletter2333** [comment]
See #489
