### ISSUE TITLE
Direct share does not work

### ISSUE THREAD

**Issue by terrytw** [NekoX-Dev/NekoX#497]
I found that there is a direct share option in Neko X, however when I tried to use it, it does not seem to work. 
![Screenshot_20210504-133744__01](https://user-images.githubusercontent.com/24227628/116964700-bf789500-acde-11eb-8a58-2a5288ac43ee.jpg)
I am using Oneplus 5T oxygen OS 10.0.2 based on Android 10

**Comment by luvletter2333** [comment]
Please provide more infomation.

What happens on your phone and what's your expected behavior.

**Comment by terrytw** [comment]
It's fairly straight forward, I use share function in chrome for Android, expected NekoX to show up in direct share menu, but it did not. I am not sure what more info you need.
