### ISSUE TITLE
Instant chrash after update from 7.6.0-2 to 7.7.2

### ISSUE THREAD

**Issue by DrDustwolf** [NekoX-Dev/NekoX#503]
After the update (ARM64-V8A) via f-droid. I always get an instant chrash of nekogramx when I try to open it.

**To Reproduce**
1. Go to f-droid
2. Click on update
3. Install it
4. Open the Application

**Smartphone (please complete the following information):**
 - Device: Lenovo Yoga Tab 3 Plus LTE (YT-X703L)
 - OS: LineageOS 18.1

**Additional context**
I needed to pick arm64-v8a manually from F-Droid it autoselects the wrong one (ameabi-v7a).
Even manually downgrading wouldn't did the issue. So I had to uninstall and reinstall it.
I first tried the version 7.7.2 again. But it again chrashed. So I went with the previous version again.
I had to do every do the activation for all my accounts again. As well as the settings for nekogramx.
I've didn't collected logcat-files because I hadnt this much time and I thought others would probably run into the same troubles and report about them here. After I checked for bug reports about this here and I didn't find any about this issue I decided to post about it myself despite I've didn't collected any log-files or screenshots.

**Comment by Xi-PP** [comment]
To F-Droid users:
The latest version of F-Droid (7.7.2.299) has a known issue where NekoX crashes immediately after startup. Please do not update NekoX in F-Droid and wait for the next version.

The GitHub version is not affected.

Source; https://t.me/NekogramX

**Comment by RaymondSchnyder** [comment]
Is there any fix for the fdroid version in sight?
