### ISSUE TITLE
can't use proxy at start

### ISSUE THREAD

**Issue by reg3xp** [NekoX-Dev/NekoX#513]
**Describe the bug**
Nekogram can't connect to socks proxy at the start (login), i have to force stop the app then launch it again for it to work

**Smartphone (please complete the following information):**
 - Device: samsung s10
 - OS: android 11
 - Version 7.6.0

**Comment by luvletter2333** [comment]
Can’t reproduce in my side

**Comment by reg3xp** [comment]
You have to uninstall the app and install it again in order to reproduce it.

**Comment by reg3xp** [comment]
Fixed
