### ISSUE TITLE
Unable to import "Yaml" Subscription for Clash node

### ISSUE THREAD

**Issue by Gherkashen** [NekoX-Dev/NekoX#519]
**Describe the bug**
I can't import this Clash subscription node: 
https://gitea.com/proxypools/sub/raw/branch/main/clash/clash.yaml
While i use it in "Clash for Android" with no issue (Yaml format).

**To Reproduce**
1. Go to 'Proxy'
2. Click on 'Add subscription'
3. Add https://gitea.com/proxypools/sub/raw/branch/main/clash/clash.yaml then, save
4. See error!

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung A70
 - OS: Android 11
 - Version: v7.7.2-2

**Additional context**

**Comment by luvletter2333** [comment]
It contains an improper YAML explicit typing tag:

>   - {name: 🇨🇳 CN_11, server: 221.228.99.36, port: 8888, type: ss, cipher: aes-256-cfb, password: !<str> 123}

which should be 

>  - {name: 🇨🇳 CN_11, server: 221.228.99.36, port: 8888, type: ss, cipher: aes-256-cfb, password: !!str 123}

And the latter format is supported by SnakeYAML.
