### ISSUE TITLE
full compatibility NekoX with TelegramFOSS f-droid's ones.. FR

### ISSUE THREAD

**Issue by DI555** [NekoX-Dev/NekoX#523]
**Is your feature request related to a problem? Please describe.**
possibilities of app change/update between NekoX and TelegramFOSS

**Describe the solution you'd like**
please, provide another builds in f-droid repo, but with app name:
'org.telegram.messenger' and with build nubmers equal to their TelegramFOSS original major build numbers.
(i mean for example for all 7.7.2/7.7.2-x the build numbers 22931/v7a and 22935/v8a)
so, could be possible make an update 'over' between NekoX and TelegramFOSS !!!

**Describe alternatives you've considered**
getting root on android

**Additional context**
so, with the same f-droid signature and equal buld number could be possible make an update from/to/between NekoX and TelegramFOSS !!!

**Comment by luvletter2333** [comment]
Build by yourself

**Comment by DI555** [comment]
yep, i see it's an easy way..
