### ISSUE TITLE
unable to add v2ray node in subscription 

### ISSUE THREAD

**Issue by Gherkashen2** [NekoX-Dev/NekoX#542]
**Describe the bug**
When I add this url in Subscription at Group, it loads nothing while it should load many v2ray proxies:
https://raw.githubusercontent.com/webdao/v2ray/master/nodes.txt

**To Reproduce**

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: [e.g. Android8.1]
 - Version [e.g. 5.15.0]

**Additional context**

**Comment by AnotiaWang** [comment]
The nodes in the TXT file aren't in correct v2ray node format. You should ask the node repo's maintainer.
