### ISSUE TITLE
“启用VPN时关闭代理”功能 bug

### ISSUE THREAD

**Issue by AnotiaWang** [NekoX-Dev/NekoX#549]
**Describe the bug**
打开“启用VPN时关闭代理”功能后，先打开内置代理，然后启用VPN，NekoX不会自动关闭内置代理。以下两种情况都有出现：

1. NekoX未启动时已启用VPN，打开NekoX时它不会关闭内置代理
2. 已启动NekoX，在使用时启用VPN，NekoX不会关闭内置代理

**To Reproduce**
1. 在喵设置中打开“启用VPN时禁用代理”功能
2. 打开系统VPN
3. The bug shall appear.

**Logcat**
https://t.me/c/1151172683/84093

**Expected behavior**
NekoX应当自行关闭内置代理。

**Screenshots**
![IMG_20210612_085053.jpg](https://user-images.githubusercontent.com/62269186/121760163-eaff6280-cb5b-11eb-9073-48ca829181a5.jpg)
![IMG_20210612_085043.jpg](https://user-images.githubusercontent.com/62269186/121760170-f05cad00-cb5b-11eb-98c7-a596fc9a7a83.jpg)

**Smartphone**
 - Device: OnePlus 9 Pro
 - OS: Android 11
 - NekoX Version: 
```
Nekogram X v7.7.2-5 arm64-v8a full release
AndroidLibV2rayLite v23, V2fly-core v4.37.2
```

**Additional context**
另外一台使用 EMUI 11 的华为设备也出现了这个问题。

**Comment by Ashinch** [comment]
我的是开vpn后会自动关代理，但是之后关了vpn后代理不会自动打开，不知道是不是有这个功能。

**Comment by AnotiaWang** [comment]
> 我的是开vpn后会自动关代理，但是之后关了vpn后代理不会自动打开，不知道是不是有这个功能。

目前应该没有这个功能吧，设置里只有“启用VPN时关闭代理”
