### ISSUE TITLE
直接分享增加发送到收藏夹

### ISSUE THREAD

**Issue by UnderCooled** [NekoX-Dev/NekoX#550]
经常用 Telegram 来收藏东西，方便 PC 和手机互通而不依赖特定浏览器插件，但官方版 Telegram 不支持在安卓的“直接分享”列表里显示收藏夹作为目标，只会显示几个最近联系人，要发送到收藏必须从下方应用列表中选择 Telegram 再选择收藏夹作为目标，比较麻烦，希望 NekoX 能支持这个功能。

**Comment by AnotiaWang** [comment]
直接转发到收藏夹不就行了？？

**Comment by UnderCooled** [comment]
> 直接转发到收藏夹不就行了？？

是指通过 分享->NekoX->选择收藏夹->确定转发 这个过程？这个过程可能要滚动分享列表并点好几下，直接分享只需要一下。

**Comment by UnderCooled** [comment]
哦，明白了，你是指浏览器收藏夹，但有的内容我不是用来在浏览器打开的，可能跨浏览器，也可能是网盘下载器，也可能直接是图片之类的，Telegram 的收藏比较方便。

**Comment by AnotiaWang** [comment]
> > 直接转发到收藏夹不就行了？？
> 
> 是指通过 分享->NekoX->选择收藏夹->确定转发 这个过程？这个过程可能要滚动分享列表并点好几下，直接分享只需要一下。

既然有更简单的步骤，为什么开发者要费时费力支持一个更绕的呢

**Comment by UnderCooled** [comment]
> > > 直接转发到收藏夹不就行了？？
> > 
> > 
> > 是指通过 分享->NekoX->选择收藏夹->确定转发 这个过程？这个过程可能要滚动分享列表并点好几下，直接分享只需要一下。
> 
> 既然有更简单的步骤，为什么开发者要费时费力支持一个更绕的呢

我那是问句，我说的就是现在的方法更绕啊，您是没用过 Telegram 的收藏夹或是分享内容到 Telegram 收藏夹吗？

**Comment by AnotiaWang** [comment]
> 我那是问句，我说的就是现在的方法更绕啊，您是没用过 Telegram 的收藏夹或是分享内容到 Telegram 收藏夹吗？

我的官方 Telegram 分享列表里有显示收藏夹

**Comment by AnotiaWang** [comment]
不好意思，之前理解错你的意思了

**Comment by UnderCooled** [comment]
我看了下源代码，在 [MediaDataController.java#L3414](https://github.com/NekoX-Dev/NekoX/blob/b3f25718b1a7d0c934f61c533d163a6613662f17/TMessagesProj/src/main/java/org/telegram/messenger/MediaDataController.java#L3414) 这里，"Saved Messages" 的对话被限制成不会提升权重，实际上后面 `installShortcut` 函数也并没有禁止 "Saved Messages" 显示到直接分享菜单当中。我不知道最开始 @DrKLO 这位安卓版开发者为啥这样设计。如果能加一个设置开关，让 "Saved Messages" 能正常提升权重，对于使用 "Saved Messages" 的人来说会方便很多。
鄙人实在是没能力折腾安卓开发环境，也不太懂安卓开发，但这个功能应该还是能实现的吧？
