### ISSUE TITLE
The search button in saved messages is unlabelled

### ISSUE THREAD

**Issue by hamsajaisal** [NekoX-Dev/NekoX#582]
**Describe the bug**
A clear and concisef whathe bug is.

**To Reproduce**
1. Go to '..

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: [e.g. Android8.1]
 - Version [e.g. 5.15.0]

**Additional context**
The search button on the top right of the saved messages not labelled. The screen reader only says button. Please label the name as search.

**Comment by luvletter2333** [comment]
Fixed, thank you
