### ISSUE TITLE
Crash upon oppening the app

### ISSUE THREAD

**Issue by juh9870** [NekoX-Dev/NekoX#591]
https://pastebin.com/7GkZuc2T

Redmi note 5 pro
Android 8.1.0
MIUI 10.3

Crash appeared after updating to the latest version posted in official telegram channel

**Comment by wodim** [comment]
Seems like data corruption to me

**Comment by erneandroid** [comment]
@wodim This is a test message to verify if the github is connected.

**Comment by luvletter2333** [comment]
We cannot know what's happening unless useful log is provided
