### ISSUE TITLE
Ability to copy link of image only messages

### ISSUE THREAD

**Issue by Y-T-G** [NekoX-Dev/NekoX#604]
**Is your feature request related to a problem? Please describe.**
You can copy direct links to telegram text messages using the context menu. But if the message is just image with no caption, that option is doesn't appear in the context menu.

**Describe the solution you'd like**
Add a 'Copy Link' option for image only messages too.

**Comment by Younes-L** [comment]
The touch target for a message is the entire width of the screen, so you can tap the empty space left or right of an image-only message to access the context menu where you'll find the Copy Link option

![Screenshot_20210808-140014_cropped](https://user-images.githubusercontent.com/23421600/128632858-9c49a1ba-1982-4a1c-b20b-77817f9641f4.png)

**Comment by Y-T-G** [comment]
Ah ok, that works
