### ISSUE TITLE
Dedicated notification option for mentions and replies in a muted chat or group.

### ISSUE THREAD

**Issue by Rtizer-9** [NekoX-Dev/NekoX#605]
**Is your feature request related to a problem? Please describe.**

I have lots of chats, groups and channels for which I completely turn off the notifications but there are times when I do want a notification.

**Describe the solution you'd like**

An option to notify the user in a muted chat or group will be really helpful when somebody replies to your chat or mentions you specifically. 

For eg: Just like nekogram, there are several other app group where you obviously don't want notification for every bug or message sent by other people but there are times when you report a bug or engage in a conversation with the developer or anybody else and obviously there are times when the person replies you at a later time and for that a notification when somebody has specifically replied to your chat or mentioned you will be really helpful.

**Comment by Younes-L** [comment]
The feature you're describing is already how telegram works (including any telegram fork such as this one).
You **will always receive a notification in muted chats** when someone
* replies to you, 
* mentions you, 
* or pins a message with notify option enabled.

NOTE : make sure you use nekox's built-in, in-app settings to mute your chats, **not android system settings**.
To do this you may either mute chats one by one or all groups/channels in a few taps : 
* Open nekox
* Open navigation drawer (swipe from the left side or tap burger icon)
* Tap "settings" then "notifications and sounds"
* Turn off "Groups" and "Channels" or tap their text label for more customisation.

In case you already turned off notifications for your chats in **android settings, turn them back on.**

Alternative : if you send a message using the channel comments feature, and someone replies to that message, you'll receive a notification and a notification message in a dedicated chat named "Replies".
This "Replies" chat is not muted if you mute groups and channels, you can still mute it separately.

**Comment by Rtizer-9** [comment]
Oh, I didn't know this is how it worked. Thanks, I'll follow the suggested steps.

**Comment by Rtizer-9** [comment]
Just wanted to let you know, I now understood that I was actually facing the problem due to using a non gcm build. I've now installed gcm build and now it works.
