### ISSUE TITLE
Add a option to forbidden swipe gesture

### ISSUE THREAD

**Issue by hosxy** [NekoX-Dev/NekoX#607]
**Is your feature request related to a problem? Please describe.**
 It often conflict to my system gesture
on my system, swipe left or right from the edge of sc
reen is "Go Back"

**Describe the solution you'd like**
add a option to forbidden swipe gesture

**Describe alternatives you've considered**

**Additional context**

**Comment by luvletter2333** [comment]
Mostly it’s your system problem, or just you need to start swipe closer to the Eddie of your screen.
