### ISSUE TITLE
Have no bubbles in chat

### ISSUE THREAD

**Issue by legacychimera247** [NekoX-Dev/NekoX#620]
**Is your feature request related to a problem? Please describe.**
No, it's just a nice idea

**Describe the solution you'd like**
Well, it would be nice to have no bubbles at all in chats, like TelegramX does, i find chats to be much clearer

**Comment by MrNessuno** [comment]
+1 
I really love the non-bubbled chat but is impossible to find it in an app that isn't Telegram X, please add it <3
