### ISSUE TITLE
Have saved messages divided in categories

### ISSUE THREAD

**Issue by legacychimera247** [NekoX-Dev/NekoX#623]
**Is your feature request related to a problem? Please describe.**
No, it's just an easier way to organize your saved messages

**Describe the solution you'd like**
Would be nice to have tabs on the saved messages chat divided per type, it's much more clearer than having to scroll an infinite list of objects/messages and so on...

**Comment by luvletter2333** [comment]
![Screenshot_20210905-123141~2](https://user-images.githubusercontent.com/31475650/132115343-f32c9134-c0d4-4c01-8b6d-ce723b417484.png)

**Comment by legacychimera247** [comment]
I know but that's an unnecessary tap more, while telegram x has this by default, being much more handy
