### ISSUE TITLE
Customizable Classic theme from the official app

### ISSUE THREAD

**Issue by janTaja** [NekoX-Dev/NekoX#625]
**Is your feature request related to a problem? Please describe.**
Nekogram X has all the customizable themes the official app has, except for the Classic one. This theme is the only one that has outcoming messages with light background and black text color: all the others have white text color.

I want to have outcoming messages with light background and black text because this way they’re easier to read in daylight and I just prefer it aesthetically, but apparently there is no way to do so in Nekogram X without having to create my own themes from scratch, which is a tedious job.

**Describe the solution you'd like**
Add the Classic theme from the official app.

**Describe alternatives you've considered**
Adding an option to customize the text color of the outcoming messages. The theme makes more sense though, I mean it is there in the official app.

**Additional context**
Nekogram X already has a Classic theme, which is different from the official Classic and is closer to Arctic. I think it should be either removed or renamed (to Standard or Neko or wherever it’s from, for example) for consistency with the official app, although the official theme can be added with a different name too.

The Classic theme in Telegram 8.0.0:
![Screenshot_20210909-164614_Telegram.jpg](https://user-images.githubusercontent.com/53832230/132701250-31b03d12-205a-4a3b-b7c2-7772a62cada3.jpg)

The Classic theme in Nekogram X 8.0.0:
![Screenshot_20210909-164529_Nekogram X.jpg](https://user-images.githubusercontent.com/53832230/132701482-703d8a1b-768e-434c-bd21-122d5dc13afe.jpg)

**Comment by Xi-PP** [comment]
Check `NekoX Settings» General» Use Default Theme` you moron

**Comment by janTaja** [comment]
Umm... This kinda solves it but hey, there’s no need at all to be rude.

To explain myself, I’ve seen that switch but it isn’t clear what it does and I’ve forgotten about it by the time I got to choosing the theme.

I guess I’ll edit the issue now because the way this theme is hidden is still a problem.

**Comment by janTaja** [comment]
Does silent closing mean that I should open a new issue or that I shouldn’t open issues about this at all?..
