### ISSUE TITLE
Hide Mobile number

### ISSUE THREAD

**Issue by Anonymous5945** [NekoX-Dev/NekoX#628]
Hide Mobile number option removed in new Update (8.0.0) while Saving to contact . Currently contact number will be visible to others if we save others in contact

**Comment by Xi-PP** [comment]
Try to explain properly `device model app version etc.` Because on my `Nekogram X v8.0.0 arm64-v8a miniAppleEmoji release` it's working properly.
Well there is a `check button to share your number` while saving their numbers [by default it's marked]. Or maybe your theme hiding this option.

**Comment by Anonymous5945** [comment]
![Screenshot_2021-09-16-20-24-03-733_nekox messenger](https://user-images.githubusercontent.com/56733554/133635058-50674d8e-4aea-4648-a3b6-64e8eba2ed3b.jpg)


There is no check button for hide number in  Nekogram X v8.0.0 arm64-v8a fullAppleEmoji ( redmi note 7 pro android version 10)

**Comment by Xi-PP** [comment]
Can you try changing the theme & try again? I've installed the exact same version. I really don't have this issue?l
https://t.me/addtheme/pSa031JlkTkmKh5Q

**Comment by Anonymous5945** [comment]
I tried with white theme instead of night mode (dark theme) still same

**Comment by luvletter2333** [comment]
The code about this checkbox:

https://github.com/NekoX-Dev/NekoX/blob/c4ada53b0d76f8199b5df3071e83924c9a16cff0/TMessagesProj/src/main/java/org/telegram/ui/ContactAddActivity.java#L240-L254

and the variable `needAddException` is only modified there: https://github.com/NekoX-Dev/NekoX/blob/c4ada53b0d76f8199b5df3071e83924c9a16cff0/TMessagesProj/src/main/java/org/telegram/ui/ContactAddActivity.java#L83 #

**Comment by StressFreeNetwareRepos** [comment]
But why? Was best   feature

**Comment by luvletter2333** [comment]
You may have made him/her in the the “Always Allow” list of Phone Number.
