### ISSUE TITLE
OpenCC causes Nekogram X to not respond (freeze)

### ISSUE THREAD

**Issue by D4v1dH03** [NekoX-Dev/NekoX#641]
**Describe the bug**
When inputing some Chinese charcters and use the OpenCC convert button the app freezes

**To Reproduce**
1. Go to any group chat
2. Input some Chinese text
3. Press three vertical dots in the message box 
4. Press OpenCC
5. App freezes

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

logs sent at
https://t.me/c/1151172683/107761

**Expected behavior**
The OpenCC conversion menu should pop up

**Screenshots**
![Screenshot_20210927-122200.jpg](https://user-images.githubusercontent.com/81270448/134971681-e63a7cf8-7aae-41c3-8bfc-7c9300679e50.jpg)

**Smartphone (please complete the following information):**
 - Device: Oneplus 8T
 - OS: Android 11
 - Version 8.1.1

**Additional context**
Reproduces intermittently, sometimes works fine but other times not working

**Comment by arm64v8a** [comment]
fixed
