### ISSUE TITLE
Ability to change app name, notification icon & app icon

### ISSUE THREAD

**Issue by D3ZOXY** [NekoX-Dev/NekoX#651]
Please add the ability to change the name of the application (to Telegram), the notification icon (to the standard one from Telegram), as well as the application icon (from Telegram or to other additional official application icons).

**Comment by shuvashish76** [comment]
Application name & icon can be changed using your launcher. (for ex: [Lawnchair](https://github.com/LawnchairLauncher/lawnchair))
& there are lots of icon pack apps available (for ex: [Arcticons](https://github.com/Donnnno/Arcticons))

IMO, optional inbuilt app icon/name etc feature is unnecessary.
Besides that why not let NekoX devs use their choice of app branding (name & logo), the app is opensource & free anyway.

Thanks!
