### ISSUE TITLE
"ignore muted unread count in folder tab" option does not work

### ISSUE THREAD

**Issue by soredake** [NekoX-Dev/NekoX#654]
**Describe the bug**
Even with this option enabled still see unread counter from pinned channels.

**To Reproduce**
1. Install nekox
2. Pin some channels.
3. See unread counter on folder tab.

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**
Does not show unread counter from pinned channels if this option is enabled.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Redmi Note 5 Pro
 - OS: Android 11
 - Version 8.1.2-1-rc01 NekoX-miniAppleEmoji-arm64-v8a-release.apk

**Additional context**

**Comment by luvletter2333** [comment]
Expected behavior, pinned channels are counted even muted

**Comment by soredake** [comment]
> Expected behavior, pinned channels are counted even muted

Is there option to disable this?

**Comment by soredake** [comment]
In official telegram android client pinned channels/chats are not counted IIRC.

**Comment by arm64v8a** [comment]
Expected behavior
