### ISSUE TITLE
Text is overlapping when long translation are used

### ISSUE THREAD

**Issue by Daviteusz** [NekoX-Dev/NekoX#656]
**Describe the bug**
Text is overlapping when long translation are used. 

**To Reproduce**
1. Change language to polish
2. Go to 'Ustawienia > Ustawienia Neko > Czat or Experymentalne'
    (EN) 'Settings > Neko Settings > Chat or Experimental
3. See bug

**Logcat**
Not nedded

**Expected behavior**
No more text overlapping like here:
![obraz](https://user-images.githubusercontent.com/11527277/139579519-e9692166-713a-4dc7-86e7-9efe873f487e.png)

**Screenshots**
![obraz](https://user-images.githubusercontent.com/11527277/139579220-6850030e-6ec3-4113-8d9d-d35f82935992.png)
![obraz](https://user-images.githubusercontent.com/11527277/139579233-a7c52662-fc24-42b5-8200-2ecb9e89e28f.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 11
 - Version 8.1.2.2-preview1 & older versions

**Additional context**

**Comment by Blue2532** [comment]
The same overlapping is happening with Spanish translations in Neko settings Chat and Experimental sections.
![Screenshot_20211031-112433](https://user-images.githubusercontent.com/93081707/139593354-d9bda989-f212-420d-9887-55f6b6151b40.png)
![Screenshot_20211031-112445](https://user-images.githubusercontent.com/93081707/139593373-ea70ecb8-28c0-4482-be6b-09842ec938db.png)
![Screenshot_20211031-112452](https://user-images.githubusercontent.com/93081707/139593377-5eab7688-50ed-4896-9847-9deef011e4e4.png)

**Comment by arm64v8a** [comment]
does it also happen in Telegram settings?

**Comment by Daviteusz** [comment]
> does it also happen in Telegram settings?

No. Strings in Telegram settings are short. Telegram has simple options that doesn't need long translations to know them (in polish lang, anyway).

**Comment by arm64v8a** [comment]
@Daviteusz 
This also occurs in Telegram's settings if I set a very long option name.

Basically we won't help Telegram to fix their bugs, so shortening the translation is just a good way.

**Comment by Daviteusz** [comment]
Ok, I changed a few words and I used dot with some of them to short them. Anyway, it's telegram bug so I'm waiting for translations updates from weblate. Thanks for info.
