### ISSUE TITLE
The slide menu on the homepage is too high

### ISSUE THREAD

**Issue by kagura114** [NekoX-Dev/NekoX#658]
**Describe the bug**
The slide menu don't fit the screen in a good way

**To Reproduce**
1. Go to the chats
2Slide from lift
**Logcat**
(I don't think this need any logs
**Expected behavior**
The highest part of the menu is at the same height of the "Nekogram X"

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Motorola Edge s
 - OS:Android 11
 - Version 8.1.2-2-preview 1

**Additional context**
This problem doesn't appear in the versions before

**Comment by kagura114** [comment]
![Screenshot_20211031-235741-902](https://user-images.githubusercontent.com/31371264/139592038-89df1590-55d2-423c-9042-e8252d3a3706.png)

**Comment by arm64v8a** [comment]
it's a preview

fix in next version
