### ISSUE TITLE
Ghost mode

### ISSUE THREAD

**Issue by NSTAdventure** [NekoX-Dev/NekoX#659]
**Is your feature request related to a problem? Please describe.**
Due to privacy concerns not everyone want to be noticed there is already plenty of Telegram built in feature to hide Sensitive info but this is not enough

**Describe the solution you'd like**
Title said that clearly to add ghost mode where:
- no digital footprint (EX: read msg without notice)
- make Profile Information invisible without change profile name for example

**Describe alternatives you've considered**
No alternative

**Additional context**
Reference:
https://cibu.io/telegram/how-to-activate-telegram-ghost-mode/

**Comment by luvletter2333** [comment]
Won't

**Comment by NSTAdventure** [comment]
> Won't

Why? 🙏😔

**Comment by luvletter2333** [comment]
Violent tos
