### ISSUE TITLE
public proxy can't link

### ISSUE THREAD

**Issue by xyskwjy** [NekoX-Dev/NekoX#661]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arm64v8a** [comment]
Are you a DC4 user?

Connections to DC4 was broken by the [Fix stream video](https://github.com/NekoX-Dev/NekoX/commit/ef9a38a10465ff0959229150dd6f13e9425bda49) commit.

We will fix it in the next verison.

**Comment by xyskwjy** [comment]
> Are you a DC4 user?
> 
> Connections to DC4 was broken by the [Fix stream video](https://github.com/NekoX-Dev/NekoX/commit/ef9a38a10465ff0959229150dd6f13e9425bda49) commit.
> 
> We will fix it in the next verison.



> Are you a DC4 user?
> 
> Connections to DC4 was broken by the [Fix stream video](https://github.com/NekoX-Dev/NekoX/commit/ef9a38a10465ff0959229150dd6f13e9425bda49) commit.
> 
> We will fix it in the next verison.

荣耀V30手机，最新的v8.1.2-3-rc1。后面换回v8.1.2后正常了。

**Comment by arm64v8a** [comment]
已修复，请用新版。
