### ISSUE TITLE
Disable sponsored messages

### ISSUE THREAD

**Issue by pavlukivan** [NekoX-Dev/NekoX#668]
Sponsored messages are slowly being rolled out. The official way of disabling them will be paid and probably server-side. I think a client-side adblock solution is necessary (at the cost of increasing the tension with upstream).

**Comment by pavlukivan** [comment]
could you at least clarify why you closed this?

**Comment by exathedev** [comment]
@pavlukivan  This option has already been added in this commit:
https://github.com/NekoX-Dev/NekoX/commit/a097f876777f1ed1a156aa272b2a70e7a977f460#diff-6efae0b0d59533ad47e55cfc0233d4136ddbafe5f97770be03ecbb06b3c4f00a
To activate it, you need to use a third-party API during sign-in in the next Nekogram release.
