### ISSUE TITLE
[FR] message sending time show in seconds

### ISSUE THREAD

**Issue by BraveSail** [NekoX-Dev/NekoX#671]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
add a switch to determine whether the sending time is displayed in seconds

**Describe alternatives you've considered**

**Additional context**

**Comment by Thatisjigen** [comment]
I'm missing the seconds timestamp too, I've recently switched from nekogram to nekogram x and it is the only feature missing.
I know i can compile a modded version with it but would be nice having it inbuilt in the released app

**Comment by BTrKR7bQyDzEY** [comment]
Just switched from nekogram and missing this feature as well.
