### ISSUE TITLE
Add option for disable counting pinned chats/channels in folder tab

### ISSUE THREAD

**Issue by soredake** [NekoX-Dev/NekoX#672]
**Is your feature request related to a problem? Please describe.**
When channel/chat is pinned in nekox, it's counted in folder tab, which is not the case in official telegram client, so i want an option to disable this.

**Describe the solution you'd like**
Having option to disable this.

**Describe alternatives you've considered**

**Additional context**

**Comment by arm64v8a** [comment]
No
