### ISSUE TITLE
点击复读时崩溃（仅发生这一次）

### ISSUE THREAD

**Issue by YuMore233** [NekoX-Dev/NekoX#678]
Process: nekox.messenger
PID: 10735
UID: 10268
Flags: 0x30983e44
Package: nekox.messenger v468 (8.2.7-play)
Foreground: Yes
Process-Runtime: 14257
Build: OnePlus/OnePlus8Pro_CH/OnePlus8Pro:11/RP1A.201005.001/2110091916:user/release-keys

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'OnePlus/OnePlus8Pro_CH/OnePlus8Pro:11/RP1A.201005.001/2110091916:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-11-22 09:45:28+0800
pid: 10735, tid: 12461, name: RenderThread  >>> nekox.messenger <<<
uid: 10268
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7d58184fc0
    x0  00000000064fa247  x1  0000007e5f92a164  x2  0000007b01184498  x3  0000000000000020
    x4  0000000000000010  x5  0000007b6e255498  x6  0000007e6559f000  x7  000000000000bce4
    x8  b400007d58184fc0  x9  b400007c8e2406e0  x10 0000000000000000  x11 0000000061abe318
    x12 00000000307ae41a  x13 000000000000deec  x14 0000000000005607  x15 00000000307a96ac
    x16 0000000000003868  x17 0000007e5f8e6e30  x18 0000007af1cd6000  x19 b400007bce238760
    x20 b400007bce238780  x21 b400007b8e2bd7d0  x22 b400007c8e2406e0  x23 00000000064fa247
    x24 b400007c8e240700  x25 b400007b8e2c8c90  x26 b400007b8e2c9380  x27 b400007b8e2c9388
    x28 b400007b8e2cf808  x29 0000007b011844d0
    lr  0000007e634530f0  sp  0000007b011844d0  pc  0000007e63453108  pst 0000000020001000

backtrace:
      #00 pc 00000000006f2108  /system/lib64/libhwui.so (android::BlobCache::clean()+100) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #01 pc 00000000006f18e4  /system/lib64/libhwui.so (android::BlobCache::set(void const*, unsigned long, void const*, unsigned long)+856) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #02 pc 000000000021f3ec  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::ShaderCache::store(SkData const&, SkData const&)+364) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #03 pc 00000000005fe7e8  /system/lib64/libhwui.so (GrGLProgramBuilder::finalize(GrGLPrecompiledProgram const*)+1660) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #04 pc 00000000005fe02c  /system/lib64/libhwui.so (GrGLProgramBuilder::CreateProgram(GrGLGpu*, GrRenderTarget*, GrProgramDesc const&, GrProgramInfo const&, GrGLPrecompiledProgram const*)+596) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #05 pc 00000000005eff74  /system/lib64/libhwui.so (GrGLGpu::ProgramCache::findOrCreateProgram(GrRenderTarget*, GrProgramDesc const&, GrProgramInfo const&)+268) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #06 pc 00000000005e6fd4  /system/lib64/libhwui.so (GrGLGpu::flushGLState(GrRenderTarget*, GrProgramInfo const&)+168) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #07 pc 0000000000523e3c  /system/lib64/libhwui.so (GrOpFlushState::executeDrawsAndUploadsForMeshDrawOp(GrOp const*, SkRect const&, GrPipeline const*)+392) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #08 pc 000000000063acb8  /system/lib64/libhwui.so (_ZN12_GLOBAL__N_110FillRectOp9onExecuteEP14GrOpFlushStateRK6SkRect$d19cfa9c8930929443c54f678259c78c+184) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #09 pc 00000000005275e8  /system/lib64/libhwui.so (GrOpsTask::onExecute(GrOpFlushState*)+728) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #10 pc 00000000005159ac  /system/lib64/libhwui.so (GrDrawingManager::flush(GrSurfaceProxy**, int, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrPrepareForExternalIORequests const&)+1720) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #11 pc 0000000000516744  /system/lib64/libhwui.so (GrDrawingManager::flushSurfaces(GrSurfaceProxy**, int, SkSurface::BackendSurfaceAccess, GrFlushInfo const&)+132) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #12 pc 0000000000546910  /system/lib64/libhwui.so (GrRenderTargetContext::flush(SkSurface::BackendSurfaceAccess, GrFlushInfo const&)+96) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #13 pc 000000000057b530  /system/lib64/libhwui.so (SkGpuDevice::flush()+48) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #14 pc 0000000000225194  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+536) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #15 pc 00000000002220e0  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*)+416) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #16 pc 000000000022b67c  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+1248) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #17 pc 000000000022dd50  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+544) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #18 pc 000000000021af8c  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+220) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #19 pc 000000000023f5fc  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+88) (BuildId: 73bc2fd76ff97578b3bbc9639abffb51)
      #20 pc 00000000000154cc  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260) (BuildId: 4e69b93bf70ed592f0029dbd1097529e)
      #21 pc 0000000000014d90  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412) (BuildId: 4e69b93bf70ed592f0029dbd1097529e)
      #22 pc 00000000000b0088  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 3b0dd94de78a8a796f793e81b7adfbd0)
      #23 pc 0000000000050408  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 3b0dd94de78a8a796f793e81b7adfbd0)

**Comment by arm64v8a** [comment]
比较像是系统偶然崩溃
