### ISSUE TITLE
Using Some Proxies Causes the App to Crash

### ISSUE THREAD

**Issue by hamid255** [NekoX-Dev/NekoX#680]
**Describe the bug**
Adding or trying to connect to some proxies makes the app to crash.
I guess this doesn't happen with proxy servers that use IP address instead of a domain name.

Also if the app is set to use proxy and you add a proxy that makes the app to crash, then you won't be able to open the app again.

**To Reproduce**
1. Open left sliding menu
2. Tap on Proxy
3. Tap on the plus icon
4. Tap on Add Socks5 proxy (issue happens with the MTProto type too).
5. Enter this: Server: localhost, Port: 9050, leave other parts empty. (this is Orbot socks5 proxy)
6. Nekogram X crashes.
7. If the Proxy button was on, you won't be able to open the app again. (just crashes when opened)

**Expected behavior**
Not crash, stay open.

**Smartphone (please complete the following information):**
 - Device: TP-LINK Neffos C5-Max
 - OS: Android5.1
 - Version 8.2.7-rc03-arm64 (edit on Nov. 28: F-droid mini version)
 - This existed also in version 8.2.3-1-arm64.

**Additional context**
In the example above if instead of "localhost", you use 127.0.0.1, the crash doesn't happen.
Tapping on some of proxy links also causes the program to crash.
To try to reproduce this issue use proxies in this channel: https://t.me/ProxyMTProto

**Comment by ltyx8** [comment]
Indeed, after trying, version 8.0.0 has no problem

**Comment by luvletter2333** [comment]
Should be fixed now.
