### ISSUE TITLE
simple-obfs 与 obfs-local 的区别

### ISSUE THREAD

**Issue by Matcha-sama** [NekoX-Dev/NekoX#683]
Nekogram X 支持使用 Shadowsocks 代理
而绝大多数的机场选择为代理添加混淆
这时需要用到 [simple-obfs](https://github.com/shadowsocks/simple-obfs) 
在原版 SS Windows 客户端里可以调用 `simple-obfs` 插件
而 [Android 用户使用的 simple-obfs ](https://github.com/shadowsocks/simple-obfs-android) 被 Nekogram X 识别为 `obfs-local` 
这就导致部分机场的代理配置中 `simple-obfs` 无法被 Nekogram X 正确识别
复制代理配置中的混淆参数，在 `obfs-local` 中重新配置，可正常使用

**Comment by nekohasekai** [comment]
您不应该使用废弃的插件。
