### ISSUE TITLE
Some Storage Paths are not working

### ISSUE THREAD

**Issue by reg3xp** [NekoX-Dev/NekoX#689]
**Describe the bug**
Storage paths
/data/user/0/nekox.messenger/files/media
/data/user/0/nekox.messenger/cache/media
are not working (Nekox doesn't create the folder or files).
I think it has to do with the fact that Nekox now only has access to media in android permission.

**To Reproduce**
1. Go to Data and Storage
2. Click on Storage Path
3. Select one of the above

**Expected behavior**
It should have created the folder and files.

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy S10
 - OS: android11
 - Version 8.2.7-rc06-arm64 F-Droid

**Comment by reg3xp** [comment]
Bug still present in v8.3.0-preview01-arm64 arm64-v8a mini fdroidArm64Release

**Comment by luvletter2333** [comment]
These folders are created. But you cannot access them unless you have the root permission.
