### ISSUE TITLE
In v8.3.0-preview01, the option was missing "Ignore blocked user in group" 

### ISSUE THREAD

**Issue by valerafcc** [NekoX-Dev/NekoX#694]
In v8.3.0-preview01, the option was missing "Ignore blocked user in group" 

In version v8.2.7-rc06, the "Ignore blocked user in group" option is present.

I am using NekoX-mini-arm64-v8a-release version 
phone: android 10 huawei p smart z

![Screenshot_20211217_150756_nekox messenger](https://user-images.githubusercontent.com/47479172/146530203-8affe22d-97a4-4cc3-b3eb-b6b3a4852fdc.jpg)

**Comment by luvletter2333** [comment]
Removed.

**Comment by valerafcc** [comment]
I am upset, it was a very convenient and necessary option for me
