### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [NekoX-Dev/NekoX#699]
https://monitor.f-droid.org/builds/log/nekox.messenger/505#site-footer

Could you please take a look? Thanks!

**Comment by luvletter2333** [comment]
https://github.com/NekoX-Dev/NekoX/pull/692#issuecomment-998732659

This issue should be solved already, I think we need update the build script in fdroid.

**Comment by linsui** [comment]
Let's track it there. Thanks!
