### ISSUE TITLE
Silent app upgrade using Shizuku

### ISSUE THREAD

**Issue by soredake** [NekoX-Dev/NekoX#704]
**Is your feature request related to a problem? Please describe.**
[Shizuku ](https://shizuku.rikka.app/) supports updating/installing apps without a prompt on many android versions, https://github.com/redsolver/skydroid and https://github.com/tachiyomiorg/tachiyomi supports this already.

**Describe the solution you'd like**
Supporting shizuku as app upgrade option.

**Describe alternatives you've considered**

**Additional context**
![изображение](https://user-images.githubusercontent.com/5204968/147670212-d956236b-634d-4244-a541-f59724fb6652.png)
![изображение](https://user-images.githubusercontent.com/5204968/147670240-ccae0ef4-fa5c-4212-aa58-c50be19467ec.png)

**Comment by megapro17** [comment]
What fucking spam? Did you read a improvement?
