### ISSUE TITLE
I want to figure out why NekoX not supports this feature

### ISSUE THREAD

**Issue by Kikll4421** [NekoX-Dev/NekoX#712]
**Is your feature request related to a problem? Please describe.**
Yeah, that's some features that NekoX lacks, and I want to know why.

**Describe the solution you'd like**
On official client, when users want to reset 2FA password while doesn't have a recovery mail. They can wait for 7 days to Initiatie the reset manually. But there's no such opinion in NekoX, you can only delete your account permanently. Which is uncomfortable.

**Describe alternatives you've considered**
Idk, wait for your answers, thx

**Comment by luvletter2333** [comment]
Fixed in v8.4.4-rc02
