### ISSUE TITLE
Camera X support

### ISSUE THREAD

**Issue by DaniAndTheWeb** [NekoX-Dev/NekoX#714]
**Is your feature request related to a problem? Please describe.**
The native camera implementation takes poor quality photos and videos.

**Describe the solution you'd like**
Adding camera x as an option would improve greatly the quality of photos and videos taken with the app

**Comment by gigisforza70** [comment]
here is a pull request to implement camera x on telegram, unfortunately it has not been merged.  I leave the link, give it a look it could be useful to implement this function.
https://github.com/DrKLO/Telegram/pull/1607

**Comment by Thatisjigen** [comment]
++++++
