### ISSUE TITLE
Support Unified Push

### ISSUE THREAD

**Issue by DonPicciotto** [NekoX-Dev/NekoX#717]
I'm using Unified Push with a couple of service now (fedilab, schildi chat and fluffy chat), thanks to the app Gotify-UP and the Fedilab istance https://gotify.fedilab.app/ , and I have to say: it's working pretty well for me. So I was wondering if it could be possible to implement this possibility in nekogram too, I would love to have only one service in background for all my notifications.
As always thanks for your work!

**Comment by ASTechnical** [comment]
NekoX(NekoGram X) Is Different From Nekogram

**Comment by DonPicciotto** [comment]
I was referring to NekogramX of course, I'm sorry for the misunderstanding. If you think it's better I will edit the first message

16 gen 2022, 08:21 da ***@***.***:
