### ISSUE TITLE
Bot issues

### ISSUE THREAD

**Issue by NSTAdventure** [NekoX-Dev/NekoX#732]
**Describe the bug**
when login via bot you can't:
see, search and join any conversation
see incoming message

**To Reproduce**
1. login via bot token
2. try to see search and join conversation or see incoming message
3. won't work

**Logcat**

**Expected behavior**
you should able to do all of them just like normal user to 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Realme 5i
 - OS: Android 10
 - Version Realme UI 1.0

**Additional context**

**Comment by luvletter2333** [comment]
Bot login is more like to receive messages passively. You should send messages to it first.
