### ISSUE TITLE
Double underline becomes italic even in monospace

### ISSUE THREAD

**Issue by anon97945** [NekoX-Dev/NekoX#744]
**Describe the bug**
it is impossible to write `__init__` in monospace, it will automatically become italic.

**To Reproduce**
1. write `__init__` in the chat
2. mark it as mono
3. it will become italic

**Expected behavior**
write it as `__init__` in mono

**Comment by luvletter2333** [comment]
Have you tested this in official client? I think it's official behavior. We may replace official's markdown parser with our brand-new one, but this is still in progress.

**Comment by anon97945** [comment]
yes, it is a official behavior, please replace the official one, when posting snips its messing up.. Thanks.

**Comment by anon97945** [comment]
So we won't get an more coding and copy paste friendly environment? It's clearly Clientside. It just needs an option to disable markdown in Text by __ ** etc
