### ISSUE TITLE
Can't get notifications from microG.

### ISSUE THREAD

**Issue by stpnwf** [NekoX-Dev/NekoX#747]
**Does the F-droid version of the app have GCM support?** I have it installed on my phone (LOS 19 + microG), but the app does not show up under microG's Cloud Messaging option. Is it because the F-droid version lacks this option?

Since I have microG on the phone, I would like that NekoX used it for notification instead of its own background client.

**Comment by MrNessuno** [comment]
Install the play store version then. On f-droid you'll never see Google things. I also have LOS + microG but I just disabled battery optimization from Android Settings and enabled the keep-alive service + background connection in Nekogram settings and works like a charm. (you can hide the keep-alive notification too)

**Comment by stpnwf** [comment]
Thank you, I just downloaded the play store version and it works with microG. Thanks for your help.

I disabled

**Comment by stpnwf** [comment]
Thank you, I just downloaded the play store version and it works with microG. Thanks for your help.

I disabled the options you mention because I wanted to save battery. It wasn't much, but the background service used 7-9% on average on my phone.
