### ISSUE TITLE
multiple tap on chat in tablet mode redirects and jumps to the last message

### ISSUE THREAD

**Issue by fsheidaiee** [NekoX-Dev/NekoX#749]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
as you see in the video tapping multiple times or two times should redirects the chat to last message as in desktop app.

**Describe alternatives you've considered**
like desktop app in windows or nekogram app in android.
**Additional context**

https://user-images.githubusercontent.com/74687186/152641451-2c60c696-dd28-4318-a5f0-d5d6a9d559bd.mp4

**Comment by NatsumeMio** [comment]
I have implemented this feature. A pull request is ready.
