### ISSUE TITLE
Censorship threat - technical solutions? 

### ISSUE THREAD

**Issue by PeB68** [NekoX-Dev/NekoX#757]
**Censorship threat**
The government of Germany recently chose to join China, Iran and Russia censoring Telegram. 

https://en.wikipedia.org/wiki/Government_censorship_of_Telegram_Messenger

https://netzpolitik-org.translate.goog/2022/nach-gespraechen-mit-bundesregierung-telegram-sperrt-erstmals-kanaele-in-deutschland-wegen-lokalen-gesetzesverstoessen/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de

**Discussion on reddit**
https://www.reddit.com/r/technology/comments/slx8fv/germany_vows_to_combat_hate_speech_extremism_on/

**Technical solutions?**
Are there technical solutions for this growing threat of censorship? 
Telegram seems to censor the search results as well.

**Comment by daiaji** [comment]
Nekogram X seems to have v2Ray built in, at least v2Ray is very effective against Chinese censorship, so maybe it should work against German censorship.

**Comment by PeB68** [comment]
Thanks for the input.

It seems it's not exactly clear how these new censorship measures are technically executed. 

Some (media outlets) claim they are linked to the country SIM card cell phone number one is registered with at Telegram.

Others report that with FOSS Telegram and NekoX everything is working.

**Comment by daiaji** [comment]
> Some (media outlets) claim they are linked to the country SIM card cell phone number one is registered with at Telegram.

It sounds a bit like getting the operator to reject the SMS login verification used by Telegram, but this should be bypassed by using email or using Telegram to receive the login verification information.
