### ISSUE TITLE
Share button of image sometimes missing

### ISSUE THREAD

**Issue by sunbeams001** [NekoX-Dev/NekoX#758]
**Describe the bug**
Tap on any static image, the share button (which in right bottom corner of screen) sometimes missing.

**To Reproduce**
1. At first there is no problem and the share button exist
2. Tap to view a gif 
3. Now back to the original image and the share button is missing

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**
The share button works fine

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. RedmiK30s]
 - OS: [e.g. Android11]
 - Version [e.g. 12.5EU]
 - NekoX version [8.5.1]

**Additional context**

**Comment by hhn1611245010** [comment]
Hi! I would like to work on this issue.

**Comment by sunbeams001** [comment]
> Hi! I would like to work on this issue.

Thanks, it still can be reproduced in version 8.6.2

**Comment by luvletter2333** [comment]
fixed in #822.
