### ISSUE TITLE
NekoX will Freeze when opening Secret Chat Media

### ISSUE THREAD

**Issue by rizqiimani** [NekoX-Dev/NekoX#759]
**Describe the bug**
NekoX will freeze if I open Media from Secret Chat profile screen

**To Reproduce**
1. Start a Secret Chat
2. Start receiving/sending any type of Media (in my case GIF and Image)
3. Open recipient profile through Secret Chat
4. Open any media from there (see number 3 and 2)
5. NekoX will Freeze immediately

**Logcat**
[NekoX-1644966155440.log](https://github.com/NekoX-Dev/NekoX/files/8075350/NekoX-1644966155440.log)

**Expected behavior**
Media opened without any problem

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 5 Pro
 - OS: Android 9
 - Version MIUI by xiaomi.eu 12.0.3

**Additional context**
None

**Comment by luvletter2333** [comment]
fixed
