### ISSUE TITLE
Use Custon App Icon

### ISSUE THREAD

**Issue by DI555** [NekoX-Dev/NekoX#763]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
option "Use Custon App Icon" to choose custon app icon

**Describe alternatives you've considered**
-
**Additional context**

it’s great to be an option "Use Custon App Icon" to choose the app icon , so you may see on screen an icon you preffered, even if you’ve made this icon by yourself! 👍

**Comment by LeBrick-Studio** [comment]
I guess you can use custom launcher apps for this

**Comment by DI555** [comment]
it’s a feature from famouse wa mods, and if nekox got custom icon packs support, why it couldn’t got and custom app icon either ! 👍👍👍

**Comment by DI555** [comment]
i think, you should change the lable to "was fixed" 👍👍👍
