### ISSUE TITLE
Add an option to share links directly with other apps

### ISSUE THREAD

**Issue by OrdinaryGecko** [NekoX-Dev/NekoX#768]
**Is your feature request related to a problem? Please describe.**
I'm not able to share a link contained inside a message directly with other apps. Only options available after long pressing a link are **Open**, **Copy** and **QR Code**.

![b4f18d12-56c1-4b48-b4da-9d5277fb49df-small](https://user-images.githubusercontent.com/92624591/156115073-7f61c26e-381e-4122-937d-9ab24e93e6ef.jpg)
_Nekogram X_

**Describe the solution you'd like**
Add a **Share** option which opens the default Android share menu after long pressing a link.

![280df436-a514-453b-8c87-cfd29e479d4a-small](https://user-images.githubusercontent.com/92624591/156115146-7826e91c-eda0-4239-b4af-9559d7811302.jpg)
_Telegram X_

**Comment by NatsumeMio** [comment]
I'm working on this feature and will open a pull request to implement it.

**Comment by luvletter2333** [comment]
Merged in 1c123de.
