### ISSUE TITLE
Can't send picture from gallery

### ISSUE THREAD

**Issue by zetpain** [NekoX-Dev/NekoX#776]
Can not send any picture from gallery correctly, instead there is black blank picture that even can't be send.

1. Go to Gallery app on Miui
2. Click on Send, "Select Nekogram X"
3. Click to any chat and try to send picture

**Logcat**
>  @`#issue.
[NekoX-1646275101599.log](https://github.com/NekoX-Dev/NekoX/files/8225675/NekoX-1646275101599.log)
`

![Screenshot_2022-03-10-22-30-07-781_nekox messenger](https://user-images.githubusercontent.com/53578224/157721104-e46ea630-2724-4d7b-8a3e-93e1534bd3e9.jpg)

![IMG_20220310_223056](https://user-images.githubusercontent.com/53578224/157721210-aa7e7dcc-2244-4874-b772-c6f2d7bdc6e6.jpg)

 - Device: Mi 11 Lite 4G
 - OS: Miui 12.5.6
 - Version: 8.5.4

**Comment by luvletter2333** [comment]
fixed in official update.
![image](https://user-images.githubusercontent.com/31475650/158398059-c2ab03f4-d414-4a86-8a2f-12a160d80ee5.png)
