### ISSUE TITLE
加入新群组提示加入太多，请退出一些

### ISSUE THREAD

**Issue by kissunyeason** [NekoX-Dev/NekoX#777]
加入新群组提示加入太多（500+），请退出一些，但是其实只有十多个，退出几个之后无法加入，用官方客户端可以直接加入。
版本8.5.4

**Comment by 493505110** [comment]
@kissunyeason 我也是

**Comment by starlight02** [comment]
我也出现这个问题
Me too.

**Comment by gcvl** [comment]
Suddenly have this problem too! Latest 8.5.4.

**Comment by Rounder01** [comment]
俺也一样，现在就是非常的苦恼，我以为只有我出了问题

**Comment by qingba** [comment]
@Rounder01 Me, too. I thought I was the only one with a problem.😂

**Comment by luvletter2333** [comment]
It's a restriction from telegram server.

这是telegram服务端的限制

**Comment by flybee0011** [comment]
Just test another telegram app---nekogram. Nekogram can allow the same account to join channels. So it issue is specific for nekogramX.

**Comment by luvletter2333** [comment]
This restriction is applied to NekoX's apiid, so we can do nothing
