### ISSUE TITLE
Unable to join community through mobile app

### ISSUE THREAD

**Issue by Jafhus** [NekoX-Dev/NekoX#778]
**Describe the bug**
Unable to join community through mobile app... It's telling to leave groups or channel, after leaving more than one group/channel could not be able to join community

**To Reproduce**
1. Go for a channel 
2. While trying to click on join its shows error 
3. Screen shot attached 

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**
Should be able to join a community 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: MI11X
 - OS: Android 12 
 - Version  
![Screenshot_20220311-234222](https://user-images.githubusercontent.com/101424691/157932067-db09232d-9809-4f65-8028-0861338ef1fa.png)
Nekogram X v8.5.4-play arm64-v8a miniPlay release
**Additional context**

**Comment by gcvl** [comment]
Confirmed, +1. Latest 8.5.4 on all my devices, not happening with Telegram X and Telegram FOSS.

**Comment by shethk94** [comment]
Same here! 
Can join from official telegram app but can't join from neko x. Even tried with different accounts.
Device : Poco F1
Rom : A12 
nekox 8.5.4 full gcm/ no gcm both have issue.

**Comment by Rounder01** [comment]
The same, on my pc,i can join in the official telegram,but can't on my mobile phone via neko X

**Comment by flybee0011** [comment]
Just test another telegram app---nekogram. Nekogram can allow the same account to join channels. So the issue is specific for nekogramX.

**Comment by d2184** [comment]
it' true,only Nekox has this problem

**Comment by jpzex** [comment]
Same issue here, latest stable 8.5.4 nekox mini armv7a nogcm from @NekoXAPKs

**Comment by bananarang1** [comment]
@Jafhus I have the same problem as well using NekoX-v8.5.4-full-arm64-v8a-release on my S21U, Android 12.

**Comment by Nuc1eoN** [comment]
May I ask why this has been closed?

I am also experiencing this issue..

NekoX v8.7.4
