### ISSUE TITLE
"Too Many Subscriptions" 

### ISSUE THREAD

**Issue by ELStrickland** [NekoX-Dev/NekoX#779]
I receive the message that I have reached my limit on groups and channels, the limit being a total of 500, although I only belong to a total of 100.

**Comment by asphyxiamywife** [comment]
https://t.me/NekogramX/545

**Comment by ELStrickland** [comment]
Thanks I started noticing this issue yesterday.

Sent from Yahoo Mail on Android 
 
  On Sat, Mar 12, 2022 at 8:09 AM, ***@***.***> wrote:   


https://t.me/NekogramX/545
