### ISSUE TITLE
BUG(Force Blur In Chat): Chat info header not blurred

### ISSUE THREAD

**Issue by MR-AliHaashemi** [NekoX-Dev/NekoX#786]
**Describe the bug**
When you open the chat (I tried with Channel), then swipe up to see the medias, You will notice that the header is not getting blurred.

**To Reproduce**
1. Go to `Settings -> Neko Settings -> General -> Force Chat Blur -> Enabled`
2. Set `Force Chat Blur` to `Enabled`
3. Set `Chat Blur Transparent` to `65` (anything else results the same)
4. Make sure about `Settings -> Chat Settings -> Chat Blur -> Enabled`
5. Open a random channel
6. Swipe up to see the media
7. You will notice that there is no blur there

**Logcat**
See the next comment.

**Expected behavior**
Chat header get blurred while you are exploring channel's media.

**Screenshots**
Left: Official (modified) Telegram
Right: NekoX
![20220319_031056.jpg](https://user-images.githubusercontent.com/60406325/159097790-fe72f5fb-016f-4c6a-9382-52110a995362.jpg)
From `modified`, I mean I just change that `canBlur` to `return true` then built it myself.

**Smartphone:**
 - Device: Samsung Galaxy A51
 - OS: Android 11
 - Version: 8.6.1-preview02

**Comment by MR-AliHaashemi** [comment]
## logcat
[NekoX-1647647325257.log](https://github.com/NekoX-Dev/NekoX/files/8308145/NekoX-1647647325257.log)

**Comment by luvletter2333** [comment]
Can't reproduce.

**Comment by MR-AliHaashemi** [comment]
Oh, I installed the latest update now ( `8.6.2-rc01` ).
And seems like it got fixed with the latest update.
Thanks!

I gonna close the issue.

**Comment by reijhgy** [comment]
Hola dónde pongo el código

**Comment by maryanknz** [comment]
Hi what about redmi 11s i dont Have that option blur in chat , why ?
