### ISSUE TITLE
allow copying messages in groups that enabled protected content

### ISSUE THREAD

**Issue by FraMecca** [NekoX-Dev/NekoX#790]
**Is your feature request related to a problem? Please describe.**
Telegram recently added this feature:
https://telegram.org/blog/protected-content-delete-by-date-and-more
> To change users' ability to forward messages open the Group or Channel Info page > Group / Channel Type > Restrict Saving Content.

This is just a smokescreen because it is just a client limitation. Right now people are resorting to screenshots that works on desktop clients

**Describe the solution you'd like**
disable copy protection of protected messages

**Describe alternatives you've considered**
completely disable protected messages in the client, even if it seems unfair because group admins may want some privacy

**Comment by luvletter2333** [comment]
It violates Telegram's ToS and we won't implement this in NekoX.
