### ISSUE TITLE
Nekogram X disappear on Play Store

### ISSUE THREAD

**Issue by cyberboh** [NekoX-Dev/NekoX#795]
**Describe the bug**

**To Reproduce**
1. Go to `https://play.google.com/store/apps/details?id=nekox.messenger`
2. Then its Not found

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**
Its appear on play store

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Poco F3]
 - OS: [Android 12]
 - Version [-]

**Additional context**

**Comment by Sunda001** [comment]
@cyberboh It is never existed on playstore

**Comment by cyberboh** [comment]
> @cyberboh It is never existed on playstore

Bro, i always download it on PlayStore

**Comment by cyberboh** [comment]
> @cyberboh It is never existed on playstore

Webcache version if you want proof
`https://webcache.googleusercontent.com/search?q=cache:uOtJGr-lOt4J:https://play.google.com/store/apps/details%3Fid%3Dnekox.messenger%26hl%3Den_IN%26gl%3DUS+&cd=3&hl=en&ct=clnk&gl=id&client=firefox-b-d`

![1](https://user-images.githubusercontent.com/99109969/160542978-f43808a2-7518-4d21-831e-67b89607fb3a.png)

**Comment by luvletter2333** [comment]
We are waiting for Play Store's reviewing. We should be back to it soon.

**Comment by cyberboh** [comment]
@luvletter2333 any news about playstore version? till now not getting appear
