### ISSUE TITLE
使用NekoX公共代理软件会闪退

### ISSUE THREAD

**Issue by Fargolee** [NekoX-Dev/NekoX#809]
**Describe the bug**
使用NekoX公共代理软件会闪退

**To Reproduce**
1. 使用NekoX公共代理，打开软件后几秒会闪退

2. 使用自行添加的代理可以正常使用软件

 - Device: [e.g. MI11pro]
 - OS: [e.g. Android11]
 - Version [e.g.  MIUI 12.5.20

https://user-images.githubusercontent.com/42547680/162385106-a2c45f68-f793-4a11-8b06-781bef5a602c.mp4

]

**Additional context**

**Comment by luvletter2333** [comment]
开关一次 `NekoX 公共代理` 后即可
