### ISSUE TITLE
[feature] UnifiedPush support for fast notificafions for users without GMS

### ISSUE THREAD

**Issue by TheDidek** [NekoX-Dev/NekoX#810]
It would be so nice if it will be possible to use UnifiedPush as notificacion provider, it would use Google services when avilable and when not, use provider user can choose.

By that NekoX will not need separate apks anymore.

I don't know if is it possible when Telegram controls the servers, but maybe take a look at the specs.

Project webpage: https://unifiedpush.org

**Comment by luvletter2333** [comment]
It requires telegram server's cooperation.
