### ISSUE TITLE
Translations on Weblate were nuked

### ISSUE THREAD

**Issue by yarons** [NekoX-Dev/NekoX#818]
Someone with the nickname `assnekox` modified all source and translation strings to the term `assnekox`.

All the translations were removed except for several correct ones.

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/163466802-e0e33c3f-db1e-4704-b28f-9cc768e22f4c.png)

**Comment by Henry2o1o** [comment]
https://github.com/NekoX-Dev/NekoX/pull/814

**Comment by oliveiraleo** [comment]
I've logged in minutes ago and find out the translations were messed up. Please, once it's fixed let me know and I'll help translating again.

PS: Maybe some sort of user verification or cool down might help tackling issues like that in the future?

**Comment by Henry2o1o** [comment]
Here it's no problem to reset the program, at Weblate there should be a backup?

**Comment by Henry2o1o** [comment]
https://github.com/Henry2o1o/NekoX/tree/main/TMessagesProj/src/main/res/values-de

**Comment by luvletter2333** [comment]
Fixed. Thank you.

**Comment by yarons** [comment]
@luvletter2333 And another nuke.
