### ISSUE TITLE
Project issue on Weblate

### ISSUE THREAD

**Issue by NathanBnm** [NekoX-Dev/NekoX#824]
Hi. Wanted to warn you that some malicious users just destroyed your translation project on Weblate (first @assnekox, then @owlgram). I informed the Weblate team about this abusive behavior so they could be banned but maybe you can take actions on your side by reverting their contributions?

**Comment by luvletter2333** [comment]
I will restore it soon, just ignore these kidding actions.

**Comment by luvletter2333** [comment]
restored.

**Comment by WofWca** [comment]
Just curious, how did "destruction" look like?
