### ISSUE TITLE
Allow hiding messages from bots

### ISSUE THREAD

**Issue by mpldr** [NekoX-Dev/NekoX#852]
**Is your feature request related to a problem? Please describe.**
It's rather annoying to see everyone's Welcome messages or self-ads in Groups. Is these cases it would be great to have the possibility to hide that bot's messages in a group (maybe similar to how Discord handles it?)

**Describe the solution you'd like**
Open the bot's profile, press the 3-dot-menu, select [hide bot activity].

**Describe alternatives you've considered**
I can't think of any

**Comment by luvletter2333** [comment]
Maybe get banned by the official.

**Comment by mpldr** [comment]
I am not sure I understand what you mean I'm afraid. Could you explain?
