### ISSUE TITLE
v8.8.5-preview01 - the app freezes after passing PIN check

### ISSUE THREAD

**Issue by gjf** [NekoX-Dev/NekoX#864]
**Describe the bug**
After update v8.8.5-preview01 I cannot use the app: it asks for fingerprint/PIN at start and then freezes

**To Reproduce**
1. Update on 1rm64 (full with GCM) from 8.7.4 to v8.8.5-preview01
2. Start the app and try to open account

**Logcat**
Cannot use logcat as the application does not start.

**Expected behavior**
It should open my account after passing PIN check.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T Pro
 - OS: Android 11
 - Version v8.8.5-preview01

**Additional context**
Maybe it is caused I have  >5 active accounts in client?

**Comment by luvletter2333** [comment]
Have you enabled Hide All Chats?

**Comment by gjf** [comment]
preview02 - situation is the same.

**Comment by luvletter2333** [comment]
How many accounts have you logined?

**Comment by gjf** [comment]
Guys, your speed of reaction really impresses.
Thank you for your efforts!

**Comment by luvletter2333** [comment]
preview03 will be ready soon, please try it

**Comment by gjf** [comment]
> preview03 will be ready soon, please try it

Yeah the problem is fixed in latest "preview02" that is in fact preview03 )))
