### ISSUE TITLE
Secret chat backup/restore

### ISSUE THREAD

**Issue by psolikov** [NekoX-Dev/NekoX#865]
**Is your feature request related to a problem? Please describe.**
Secret chat data is lost when uninstalling an app. It is also impossible to move a secret chat to another device.

**Describe the solution you'd like**
It would be great to have at least the option to export chat data the same way as it is done in the official desktop client (html format).
Restoring the chat could be implemented as well by resending the messages (probably without timestamps).

**Comment by dishapatel010** [comment]
@psolikov Call durov xd

**Comment by psolikov** [comment]
@dishapatel010 Is there a reason it couldn't be implemented in the client?
