### ISSUE TITLE
people nearby does not work on CalyxOs

### ISSUE THREAD

**Issue by Rmtony** [NekoX-Dev/NekoX#879]
**Describe the bug**
people nearby perpetual loading on CalyxOS

**To Reproduce**

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**

**Screenshots**
![Screenshot_20220721-165415](https://user-images.githubusercontent.com/109748137/180248696-4da6478e-aae4-4bf8-bf34-839d5d9e3b5b.png)

**Smartphone (please complete the following information):**
 - Device: Google pixel 3
 - OS:  Android 12L

**Additional context**
NekoX NoGcm version

**Comment by luvletter2333** [comment]
Won't fix
