### ISSUE TITLE
option to disable quick reaction gesture 

### ISSUE THREAD

**Issue by ChaosNicro** [NekoX-Dev/NekoX#883]
**Is your feature request related to a problem? Please describe.**

I simply often have accidental double-taps on messages, leading to misunderstandings sometimes.

**Describe the solution you'd like**

Have a "None" option at the top of the emoji-selection for the quick reaction settings, that does nothing when the gesture is triggered. 

**Describe alternatives you've considered**

Alternatively there could be a separate toggle that disables the listener for double-taps completely. 

**Additional context**

**Comment by luvletter2333** [comment]
Neko Config -> Chat -> Interaction -> Reactions in menu => Disable
