### ISSUE TITLE
Force close when click icon emoji & sticker

### ISSUE THREAD

**Issue by yasirarism** [NekoX-Dev/NekoX#90]
I have updated Nekogram X to the latest version, but I still experience forced close when clicking on the emoji or sticker icon. Hopefully this problem is fixed soon.  I have tried all versions of nekogram x, either with gcm or not.

**Comment by nekohasekai** [comment]
@yasirarism 

Settings -> Click the version number -> "Enable Log"

And then click "Send Log" to https://t.me/he_llo_world in the settings

**Comment by yasirarism** [comment]
In this update has been fixed, thanks
