### ISSUE TITLE
[Issue] Editing Photo Crashes App

### ISSUE THREAD

**Issue by seniorm0ment** [NekoX-Dev/NekoX#901]
When I upload a photo then go into the editor, and try to draw on it, it always crashes the app. This has been an issue I've encountered for a few months now.

**Comment by luvletter2333** [comment]
please upload your log.

**Comment by frknkrc44** [comment]
Use "Send logs" option of NekoX or use "adb logcat" method @seniorm0ment

**Comment by gianmarcogg03** [comment]
[I tried with logcat](https://github.com/NekoX-Dev/NekoX/files/10530221/logcat.txt), but there's probably too much stuff in here, I'll leave it to you.
