### ISSUE TITLE
Antivirus has detected malware

### ISSUE THREAD

**Issue by s4velyeva** [NekoX-Dev/NekoX#908]
**Describe the bug**
After last database update built-in anti-malware software from RealmeUI 3.0 has detected rootkit malware in NekogramX.

**To Reproduce**
1. Install NekoX on RealmeUI 3.0
2. Launch built-in anti-malware software

**Smartphone (please complete the following information):**
 - Device: Realme C25S (RMX3195)
 - OS: Android 12
 - Version: Latest

**Comment by Here2comment** [comment]
¹ you mean latest version of Nekogram?

² Version: Latest? 😅 it helps devs find packages easier so I'm sure it'll be better to list the actual version

**Comment by s4velyeva** [comment]
> ¹ you mean latest version of Nekogram?
> 
> ² Version: Latest? 😅 it helps devs find packages easier so I'm sure it'll be better to list the actual version

F-Droid package.

**Comment by luvletter2333** [comment]
Stop using the wrong virus scanning software. If you don't trust NekoX, just don't use it.

**Comment by y1111** [comment]
https://github.com/NekoX-Dev/NekoX/issues/1034


seems to be related to this and its fixed in the fdroid version as it seems in the links in that issue
