### ISSUE TITLE
Add Copy selection of text option

### ISSUE THREAD

**Issue by Zeus404-XD** [NekoX-Dev/NekoX#916]
**Is your feature request related to a problem? Please describe.**
Ans:- Nope,This feature request isn't related to any bug or problem related to NekoX

**Describe the solution you'd like**
Ans:-A feature that enables the user to Copy a selection of text in a particular msg, similar to coping the entire msg but instead,a popup appears with all the contents of the msg,and there we can be able to long press and copy a particular content.

**Describe alternatives you've considered**
Ans:- I've been only coping the entire msg and deleting the other text that i dont need XP

**Additional context**
![IMG_20220904_144037](https://user-images.githubusercontent.com/86465455/188306196-d278ce28-0c8b-4681-a58b-6dd627fdd696.jpg)
Here's a image representing how the option looks in other clients

**Comment by MercWith** [comment]
@Zeus404-XD Isn't it already possible to do so,just long press on the text in a message don't really need a dedicated pop-up for it,it's counterintuitive

**Comment by Zeus404-XD** [comment]
> @Zeus404-XD Isn't it already possible to do so,just long press on the text in a message don't really need a dedicated pop-up for it,it's counterintuitive(oof ,didn't see the closed tag,lmao sry)

Yeah just after opening a feature request,i came to know that we can copy by that method..!!Thanks for helping me with a way out even tho i had closed the feature request <3
