### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [NekoX-Dev/NekoX#926]
**Describe the bug**
https://gitlab.com/linsui/fdroiddata/-/jobs/3095331633 It seems GMS is required to build NekoX v8.9.3-preview01.  Could you please take a look?

**Comment by linsui** [comment]
Thanks! Glad to hear that there will be a release version. There is no release version for a long time so I tried to add the preview version.

**Comment by Zulgrib** [comment]
Any news on this?

**Comment by luvletter2333** [comment]
We finally removed GCM parts from the codebase and only compiled it in the release build type as we used to do.

Fdroid build should work based on the main branch 27ced58f.

**Comment by linsui** [comment]
Thanks!
