### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by sminato27** [NekoX-Dev/NekoX#927]
Why the fk 36 required permissions and why my system is accusing that's a Trojan?

![Screenshot_2022-09-28-21-55-30-269_com.miui.packageinstaller.jpg](https://user-images.githubusercontent.com/59450675/192914454-fb4e4081-a7e8-4821-9ff1-00d652d7762e.jpg)

**Comment by ccelik97** [comment]
Hi. Could you please provide more info about what phone and system version do you use there? 

Additionally, please provide the checksum of that .apk file. SHA256 would do.

**Comment by sminato27** [comment]
I've installed it anyway and don't worked for my purposes, then I uninstalled but thanks for trying to help.

**Comment by ccelik97** [comment]
> I've installed it anyway and don't worked for my purposes, then I uninstalled but thanks for trying to help.

I also wonder why in your ss it shows as a 55.7 MB file meanwhile the largest file available in the same release is a [55.2 MB file]([NekoX-v8.9.3-preview01-full-x86_64-release.apk](https://github.com/NekoX-Dev/NekoX/releases/download/v8.9.3-preview01/NekoX-v8.9.3-preview01-full-x86_64-release.apk)
55.2 MB).

That's an x86_64 build btw and I doubt you installed that on your phone as your phone would have an Arm64 or armeabi-v7a architecture. That's leave as the largest file candidate you may have downloaded from this release as the [53.2 MB file](https://github.com/NekoX-Dev/NekoX/releases/download/v8.9.3-preview01/NekoX-v8.9.3-preview01-full-arm64-v8a-release.apk).

It's not a MiB to MB kind of misunderstanding either as the numbers don't add up no matter how I put it so, I'm suspecting you're not telling the whole story here.

May I go out of my way and ask you that you went out of your way to tamper with the source to add that "Trojan" yourself, only to come falsely cause a fuss about it over here?

Sorry in advance if my guess is incorrect but I really wished that you'd tell us the SHA256 checksum of that 55.7 MB file which your package installer have identified as trojan there, so we could see if it matches with any of the releases from here. Without anything to prove that you indeed acquired the file from here or the [NekoX Updates](https://t.me/NekogramX) Telegram channel, I'm afraid this issue will end up getting auto closed as resolved lol.
