### ISSUE TITLE
frequently crash

### ISSUE THREAD

**Issue by 2584191127** [NekoX-Dev/NekoX#933]
**Describe the bug**
it crashed so many times when I used.

**To Reproduce**
no any special action, just common use

**Logcat**
[NekoX-1665461929780.log](https://drfilestreambot.cf/30452/NekoX-1665461929780.log?hash=AgADNw)

**Smartphone (please complete the following information):**
 - Device: huawei p40 pro
 - OS: HarmonyOS 3.0
 - Version: Nekogram X v8.9.3-preview01 arm64-v8a mini release

**Comment by 2584191127** [comment]
[NekoX-1665461929780.log](https://github.com/NekoX-Dev/NekoX/files/9751373/NekoX-1665461929780.log)

**Comment by NikMAX2077** [comment]
I have a same problem too
