### ISSUE TITLE
荣耀70pro闪退

### ISSUE THREAD

**Issue by biange200** [NekoX-Dev/NekoX#934]
荣耀70pro 安卓12 安装的是nogcm版本
经常出现nekox闪退问题

**Comment by LUKE-GG33** [comment]
关闭自带节点试试

**Comment by biange200** [comment]
好吧  nekox的优势不就是自带代理 关闭就失去优势了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月30日 00:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NekoX-Dev/NekoX] 荣耀70pro闪退 (Issue #934) |

关闭自带节点试试

**Comment by worm001** [comment]
已测试关闭自带节点用外部加速器就正常！ 如果这个功能失去，那选择性就多了去了。
