### ISSUE TITLE
Still can see blocked persons in chat groups

### ISSUE THREAD

**Issue by WeFenFinit** [NekoX-Dev/NekoX#94]
**Describe the bug**
Messages of blocked users appear in the preview in the chat list and on reply

**To Reproduce**
Ban person, enable "ignore blocker users in group"

**Smartphone**
 - Device: LG G4c h522y
 - OS: Android 5.0.1
 - Version 6.2.0.1

**Screenshots**
Blocked person:
![image](https://user-images.githubusercontent.com/22540805/84598314-a0d19b80-ae8b-11ea-91b3-7bf9bb51574b.png)
Chat list:
![image](https://user-images.githubusercontent.com/22540805/84598287-7d0e5580-ae8b-11ea-8313-aff3284e7203.png)
Reply message:
![image](https://user-images.githubusercontent.com/22540805/84598330-c363b480-ae8b-11ea-91d5-5105a9584a05.png)
When typing:
![image](https://user-images.githubusercontent.com/22540805/84598910-ebedad80-ae8f-11ea-810f-3a04aa5ffbf4.png)

**Comment by nekohasekai** [comment]
How to reproduce this?

**Comment by WeFenFinit** [comment]
Just block person and then Settings -> Neko Settings -> Chat -> ignore blocked users in group

**Comment by nekohasekai** [comment]
@WeFenFinit can't reproduce this

**Comment by nekohasekai** [comment]
Closed because this is a closed source upstream feature
