### ISSUE TITLE
[BUG] bug in compile native libraries (Apple m1 silicon)

### ISSUE THREAD

**Issue by hosseinkhojany** [NekoX-Dev/NekoX#946]
I followed the steps mentioned for the build
And when I execute this command, I encounter a problem
./run init libs

**Logcat**
javad@javads-MacBook-Air NekoX % ./run init libs                                                                                            
>> bin/init/libs.sh
yasm 1.3.0
Compiled on Oct 23 2021.
Copyright (c) 2001-2014 Peter Johnson and other Yasm developers.
Run yasm --license for licensing overview and summary.
HEAD is now at 626ff3595 Update AUTHORS and version info in libs.mk
Build platform: darwin-x86_64
Parallel jobs: 8
Building x86...
patching file vpx_dsp/add_noise.c
Cleaning...
make: *** No rule to make target `clean'.  Stop.
Configuring...
Not a directory: /Users/khoujani/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.
HEAD is now at a77521cd5d Changelog: update
Removing ffbuild/config.log
Build platform: darwin-x86_64
Parallel jobs: 8
Building x86_64...
Cleaning...
Makefile:2: ffbuild/config.mak: No such file or directory
Makefile:40: /tools/Makefile: No such file or directory
Makefile:41: /ffbuild/common.mak: No such file or directory
Makefile:97: /libavutil/Makefile: No such file or directory
Makefile:97: /ffbuild/library.mak: No such file or directory
Makefile:99: /fftools/Makefile: No such file or directory
Makefile:100: /doc/Makefile: No such file or directory
Makefile:101: /doc/examples/Makefile: No such file or directory
Makefile:167: /tests/Makefile: No such file or directory
make: *** No rule to make target `/tests/Makefile'.  Stop.

**Comment by luvletter2333** [comment]
Building on macOS, including both x86_64 and arm64 architecture, requires additional patches for the build scripts. I don't have Apple devices with macOS, so that I won't fix it. You are welcome if you could contribute to patches.
