### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by WunderWungiel** [NekoX-Dev/NekoX#955]
NekoX stuck on 8.9.3-preview... is it abanonded?
Thanks for info

**Comment by lukemin** [comment]
CI releases only has mini Version， how can I download the latest full Version？

**Comment by WunderWungiel** [comment]
Why you don't release stable version?
Altough CI works

**Comment by driftywinds** [comment]
I feel like NekoX has been abandoned

**Comment by ferlanero** [comment]
@driftywinds I think so too

**Comment by ferlanero** [comment]
@ferlanero And it's a pitty because I dont know any other tg client without GCM integrated

**Comment by NikMAX2077** [comment]
> @ferlanero And it's a pitty because I dont know any other tg client without GCM integrated

You can try Telegram FOSS from F-Droid

**Comment by Rush-er** [comment]
> @ferlanero And it's a pitty because I dont know any other tg client without GCM integrated

You can try https://github.com/NextAlone/Nagram

**Comment by ferlanero** [comment]
@Rush-er Thanks for the suggestion! Of course I will try it

**Comment by ferlanero** [comment]
@Rush-er I have been testing Nagram for a few days and I have to admit that it is already far ahead of NekoX in terms of functionality and performance. And since it seems that NekoX has been discontinued, I encourage other users to try Nagram in its latest stable version

**Comment by selfmusing** [comment]
@ferlanero Really? Nekox discontinued 😦?

**Comment by driftywinds** [comment]
> @Rush-er I have been testing Nagram for a few days and I have to admit that it is already far ahead of NekoX in terms of functionality and performance. And since it seems that NekoX has been discontinued, I encourage other users to try Nagram in its latest stable version

I thank you for this, i have been looking for a replacement for the longest time

**Comment by ferlanero** [comment]
@selfmusing I'm afraid so

**Comment by selfmusing** [comment]
@ferlanero 💀💀💀

**Comment by amadicus** [comment]
Why are developers silent?  Would bring clarity - the client is alive or dead.

**Comment by ferlanero** [comment]
@amadicus It's obviously discontinued

**Comment by amadicus** [comment]
@ferlanero , So far, no one from the developers has confirmed, but has not denied the death of the client ((

**Comment by amadicus** [comment]
Today I received a response from the developer - the  project is alive! 


"fdroid build requires pure free software and now NekoX contains non-free google maps component in all build-type (including noGcm and fdroid version). So that's why nekox doesn't have fdroid updates and normal release level updates for months. I have been working on it since weeks ago, but I am occupied by my personal stuffs these days. Sorry for the delay, I will still continue working on this project after January 15th."

**Comment by luvletter2333** [comment]
Soon.
