### ISSUE TITLE
Option to ignore messages from blocked users disappeared

### ISSUE THREAD

**Issue by borismavrin** [NekoX-Dev/NekoX#960]
1. Go to NekoSettings
In the last version of the app from F-Droid 8.7.4 there is a lack of option to ignore messages from blocked users. 
Option exists in 8.2.7-rc03

![photo_2022-12-31_02-42-28](https://user-images.githubusercontent.com/16165379/210116836-926bb79b-a79a-49d7-b495-d60c778082c8.jpg)
![photo_2022-12-31_02-43-14](https://user-images.githubusercontent.com/16165379/210116837-0c273cee-f14d-4765-a2b9-838d08b8741d.jpg)

**Comment by the-Arioch** [comment]
just downloaded 893p01 arm64 from tg channel - and it seems a lot lost, even "ignore mnuted unread count" seems gone

**Comment by g00m00nry0ng** [comment]
I suspect there's an official request from Telegram to remove this, as it happened in Nokegram https://t.me/NekoUpdates/52

**Comment by luvletter2333** [comment]
Yes, the official email us and ask us to remove this feature.
