### ISSUE TITLE
 Integration of Mobile Coin in Telegram

### ISSUE THREAD

**Issue by baermathias** [NekoX-Dev/NekoX#988]
Dear Maintainers,

I am writing to propose a feature request for the integration of [Mobile Coin](https://mobilecoin.com/) into Telegram / NekoX. As you may already know, the Signal app recently added [support for Mobile Coin](https://www.wired.com/story/signal-mobilecoin-cryptocurrency-payments/), and it has been widely hailed as a significant step forward for both privacy and cryptocurrency adoption.

Mobile Coin is a lightweight cryptocurrency that enables private, fast, and efficient transactions on mobile devices. With Mobile Coin, users can send and receive payments without revealing their identity or personal information. This makes it an ideal fit for Telegram, which is known for its focus on privacy and security.

Here are a few reasons why I believe adding Mobile Coin support to the Telegram / NekoX would be a great idea:

Increased Privacy: By integrating Mobile Coin, Telegram users would have access to a more private and secure payment system. Mobile Coin uses zero-knowledge proofs to ensure that transactions are completely anonymous, which would be a significant improvement over existing payment options.

Faster Transactions: Mobile Coin transactions are fast and lightweight, making them ideal for mobile devices. This would be a significant improvement over existing payment options, which can be slow and clunky on mobile devices.

Positive Media Coverage: Adding Mobile Coin support to the Telegram / NekoX repository would likely attract media attention and generate positive coverage for both projects. This could lead to increased adoption and more users and Github stars for both projects.

I believe that integrating Mobile Coin into the Telegram / NekoX would be a significant step forward for both projects and would help to further cement NekoX reputation as a leader in privacy and security. I look forward to hearing your thoughts on this proposal and hope that you will consider it seriously.

Here are also two images of how this could look:

Step 1.

![step1_mobile_coin](https://user-images.githubusercontent.com/45003352/224555647-9f5137e2-e156-4674-a7b8-fd8297d4910f.png)

Step 2.
![step2_mobile_coin](https://user-images.githubusercontent.com/45003352/224555656-0d4a05bd-a10e-415f-944f-bc61c3d8177b.png)

**Comment by dic1911** [comment]
@baermathias And I believe this kind of proposal should have never be an issue of a unofficial client

**Comment by selfmusing** [comment]
@baermathias bruh 👁️👁️

**Comment by baermathias** [comment]
OK, OK I am closing the issue :-)
Will try to propose the idea to the official Telegram client repo https://github.com/DrKLO/Telegram
